### ISSUE TITLE
Debug while selling gems

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1010]
I'm getting debug when trying to sell 100 gems to npc **Tamoril**, Yalahar.
https://gyazo.com/d133f6f1efd5e616804cbb08196ee204
Only when selling **100** gems.

**Comment by kito2** [comment]
@ColorsCL this happens only when selling 100 gems.

@LastCrystal for now haven't been able to reproduce the bug with other characters. Is this happening with other characters, or just your character?

**Comment by LastCrystal** [comment]
I checked it again today and it disappeared. Can't reproduce it either, even on the same character.
Don't know why it was debugging me yesterday :s
