### ISSUE TITLE
Allow Cookie achievement

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1011]
Date | 2019-03-03 17:26:30
-- | --
Player name | Bullet Sponge
Position | 32352, 32230, 7
Description | **Player said:** The cookie delivery mission of what a foolish quest can be completed immediately without delivering the cookies (I've spoken to each npc at some point beforehand tho, if that matters), this locks you out of getting the "Allow Cookies?" achievement

**Comment by Kertie** [comment]
00:27 Congratulations! You earned the achievement "Allow Cookies?".

The achievement is working properly.

Closed.

**Comment by joseluis2g** [comment]
creo que se refiere a que solo puedes obtener este achievement en la quest
