### ISSUE TITLE
NPC Ceiron - bad words

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#1018]
Date | 2019-03-05 18:53:17
-- | --
Player name | Paah
Position | 32664, 31717, 7
Description | 18:52 Ceiron: I'm glad that you are still with me, \|PLAYERNAME\|. Especially because my next task might re < he says [PLAYERNAME] instead of the players name ^^

**Comment by Kertie** [comment]
Nothing to add here. We have to fix the dialog.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64055365-36fe3480-cb8c-11e9-86fb-08355bd1794e.png)

Now it's working properly.
Closed.
