### ISSUE TITLE
Necro task reset kills after relog

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1031]
Necromancer task resets kills after relog.
Player Sosna upload cams, on one cam his numer is over 3800, on the second one after relog and going to Grizzly Adams it shows 8 kills.

Add the correction to Sosna task in order to allow him to kill Necropharus. @kito2

**Comment by Kertie** [comment]
I think that the problem is that you can start the task talking to different NPCs.

**Comment by kito2** [comment]
Esto es debido a que hay tasks en dos NPCs/sistemas distintos: Grizzly Adams por modal window, Grizzly Adams hablandole y el NPC de RL hablandole.

Para probar este task debes ejecutar este comando con el God:
/storage playerName, 65079, 3999

Y al tener aceptada la task, matas un necromancer, y llegaras a los 4 mil. Ahi podras reportar en Grizzly hablando o con modal window, y con el NPC de RL, asi contrastaras lo que esta mal.

**Comment by Kertie** [comment]
Probé con Lugri. Ejecuté ese comando pero no me suma los necromancers.
Luego hablé con Grizzly Adams, hice el task y lo pude reportar en Lugri.
Esa mezcla debemos quitarla. Deberíamos dejar un NPC sólo, se cruzan entre sí.
El task de Lugri no cuenta las muertes, al menos a mí no me ha contado. El que da Grizzly Adams sí.
@kito2

**Comment by joseluis2g** [comment]
o hacer bien el intercambio

**Comment by joerod1** [comment]
pero son la misma tasks la de Lugri y Grizzly? O son distintas?

**Comment by Kertie** [comment]
La solución que comenté con Kito, y creimos que era la más eficiente es dejarlo como RL, sólo la task de Lugri.

De esa forma, no tenemos que trabajar en algo que no hace falta y podemos centrarnos en arreglar otros issues más importantes, ya que Lugri seguiré dando task.

**Comment by kito2** [comment]
@joerod1 lo que pasa es que la primera vez que haces la task puedes matar al Necropharus, luego de eso no puedes matarlo nunca mas.

Es por eso que genera toda esta confusion.

**Comment by Kertie** [comment]
Finally, we will keep Lugri's task and remove Grizzly Adam's one.
Closed.
