### ISSUE TITLE
Inquisition resets.

### ISSUE THREAD

**Issue by Kertie** [kito2/mtibia-bounties#1037]
![image](https://user-images.githubusercontent.com/45070560/53955592-b5948080-40d9-11e9-94d9-3a34ed32de62.png)

![image](https://user-images.githubusercontent.com/45070560/53955626-cd6c0480-40d9-11e9-8bed-91aba6539bd6.png)

**Comment by joerod1** [comment]
i could'nt reproduce this. I have taken the reward, received the reward and quest status, then i went to Henricus and i can buy the "blessing of the inquisition"

**Comment by kito2** [comment]
Fake report.

Seguramente gesior o slugar modificaron algo mientras estuvo online y yo lo reverti.
