### ISSUE TITLE
 Deathling Spellsinger corpse

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#104]
Date | 2018-12-22 00:08:12
-- | --
Player name | GM Kertie
Position | 33573, 31412, 13
Description | Deathling Spellsinger --> Its corpse --> You see an item of type 32496 (Vol:8).

**Comment by Kertie** [comment]
18:25 You see a dead deathling spellsinger (Vol:18).
Item ID: 32496
Position(31189, 32009, 6)

https://vimeo.com/334705603

It seems like if somebody fixed that time ago.

Closed.
