### ISSUE TITLE
Using exercise dummy from someone else house

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1043]
Players can you exercise wapons on exercise dummy from neighbor house
![image](https://user-images.githubusercontent.com/46424212/54001997-79026c80-414d-11e9-8b65-cf18bc203391.png)

**Comment by joseluis2g** [comment]
lmao

**Comment by kito2** [comment]
no podemos cambiar el item y su configuracion, hay que hacer un reajuste en programacion de que si el dummy esta en una casa, lo usen los invitados de la casa

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/65276607-5b648580-db28-11e9-9c5f-6d19291b75e4.png)

It's still bugged.

**Comment by joerod1** [comment]
ahh, must be the same house n?

**Comment by Kertie** [comment]
As far as I can see, it has been corrected.
Closed.
