### ISSUE TITLE
Field runes duration

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1044]
Field created from runes by players (bomb/wall/field runes)
**Poison field**
Last for 2 min but should last for 4:08 min.
**Fire field** 
The first stage last 2 min, second stage last 2 min and third stage last 2 min.
The should last: first stage 3:20, second stage 2:28, third stage 1:38.
**Energy field** 
Last for 2 min but should last for 1:38.
![image](https://user-images.githubusercontent.com/46424212/54004947-dd2a2e00-4157-11e9-9ac7-3bba85f038d1.png)

**Comment by Kertie** [comment]
- [ ] **POISON BOMB RUNE**

- MTibia's one last for 2 minutes.
- It should last for 4:08 minutes.

- [ ] **POISON FIELD RUNE**

- MTibia's one last for 2 minutes.
- It should last for 4:08 minutes.

- [ ] **POISON WALL RUNE**

- MTibia's one last for 2 minutes.
- It should last for 4:08 minutes.

___________________________________________________________________________________________________________
- [ ] **FIRE BOMB RUNE**

- [ ] - First Stage on MTibia lasts for 2 minutes.


>It should last for 3:20 minutes.

- [ ] - Second Stage on MTibia lasts for 2 minutes.


>It should last for 2:28 minutes.

- [ ] - Third Stage on MTibia lasts for 2 minutes.


>It should last for 1:38 minutes.

- [ ] **FIRE FIELD RUNE**

- [ ] - First Stage on MTibia lasts for 2 minutes.


>It should last for 3:20 minutes.

- [ ] - Second Stage on MTibia lasts for 2 minutes.


>It should last for 2:28 minutes.

- [ ] - Third Stage on MTibia lasts for 2 minutes.


>It should last for 1:38 minutes.

- [ ] **FIRE WALL RUNE**

- [ ] - First Stage on MTibia lasts for 2 minutes.


>It should last for 3:20 minutes.

- [ ] - Second Stage on MTibia lasts for 2 minutes.


>It should last for 2:28 minutes.

- [ ] - Third Stage on MTibia lasts for 2 minutes.


>It should last for 1:38 minutes.

___________________________________________________________________________________________________________
- [ ] **ENERGY BOMB RUNE**

- MTibia's one last for 2 minutes.
- It should last for 1:38 minutes.

- [ ] **ENERGY FIELD RUNE**

- MTibia's one last for 2 minutes.
- It should last for 1:38 minutes.

- [ ] **ENERGY WALL**

- MTibia's one last for 2 minutes.
- It should last for 1:38 minutes.

**Comment by joerod1** [comment]
@Kertie no entiendo eso de los stages

**Comment by Kertie** [comment]
@joerod1 el fuego tiene distintos estados, empieza más intenso y decrece la llama con el tiempo. De hecho si pasas por encima en su primer stage hace más daño que si lo pasas ya medio apagado.

**Comment by kito2** [comment]
Tiene un decay el fuego inicial con cierta duracion, luego el otro decay tiene otra duracion. Y eso significa un estado por como lo definen.

**Comment by joerod1** [comment]
i have added to all runes, except fire ones, because i don't know how to manage with duration over stages yet

**Comment by Kertie** [comment]
Sólo queda el fire, habría que hacerlo en items.xml --> modificando los fire field que tienen decay.
