### ISSUE TITLE
Exana ina doesn't break stealth ring

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1045]
Exana ina should have a chance of breaking worn stealth ring.

**Comment by joseluis2g** [comment]
wow thats new for me

**Comment by Kertie** [comment]
- [ ] It moves the ring from the equipment to your backpack.
- [ ] If you don't have a free space in your backpack, ring will be dropped on the ground.
- [ ] It has a chance to break the ring.
- [ ]

**Comment by Kertie** [comment]
It's working.
Closed.
