### ISSUE TITLE
Yasir Missing Items.

### ISSUE THREAD

**Issue by Kertie** [kito2/mtibia-bounties#1046]
1. Odd organ.
2. Instable proto matter.
3. Crystallized anger.

Also we must check 'Energy Vein' because Yasir is not today, so I couldn't check it.

**Comment by LastCrystal** [comment]
@Kertie https://github.com/kito2/mtibia-bounties/issues/892

**Comment by Kertie** [comment]
Let's close that and continue with your issue adding this. 

Thanks @LastCrystal .
