### ISSUE TITLE
Taming Ursagordon 

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1053]
Date | 2019-03-10 02:49:45
-- | --
Player name | Niebezimienny
Position | 32094, 31011, 8
Description | **Player said:** If you have Ursagordon and you use item it will dissapear and communication "You arleady have Ursagordon will apear"
Description | I guess it shouldn't use your item if you already have this mount?

**Comment by Kertie** [comment]
Item mustn't be deleted if you had the mount previously.
I took the mount and then.. I used 4 melting horns which have been deleted.

**Comment by Kertie** [comment]
Now it's working.
Closed.
