### ISSUE TITLE
carrot cake increases your shielding skill instead of distance fighting

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#1058]
Date | 2019-03-12 12:54:00
-- | --
Player name | Bullet Sponge
Position | 32657, 31907, 8
Description | carrot cake increases your shielding skill instead of distance fighting

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/63872768-9e668980-c9be-11e9-84b8-fd2ea01b6026.png)

**Comment by Kertie** [comment]
We have to change shielding into shielding on this message.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64288419-5917fe00-cf62-11e9-8f00-3742b7993b0a.png)

![image](https://user-images.githubusercontent.com/45070560/64288428-61703900-cf62-11e9-92b1-ec32aad07c37.png)

It's working properly.
Closed.
