### ISSUE TITLE
All Minotaurs walking in energy and other field

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#1059]
Date | 2019-03-12 16:29:52
-- | --
Player name | Starszy Imbir
Position | 31933, 32856, 4
Description | All Minotaurs walking in energy and other field !

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64385954-25a7a300-d038-11e9-87d5-a2ae9b14262d.png)

They shouldn't walk trough Fire, Energy or Poison.

**Comment by joerod1** [comment]
which minotaurs?

**Comment by Kertie** [comment]
It's working now.
Closed.
