### ISSUE TITLE
The Last Lore Keeper and final Thais

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1065]
It works, tested it, now is possible to obtain 3rd lvl crit this way but is so eazy.

- [ ] 1. It took like 60 seconds to kill Last Lore Keeper, when on RL has much more hp and it should take this team like 10 min instead. 
- [ ] 2. Please check his loot, it drops some ammunition that it shouldn't like (spectral bolts, diamond arrows, royal stars) also no one from team got anything good.
- [ ] 3. Last Lore Keeper should do much more dmg it did like nothing.
- [ ] 4. Animated Swords and boss should have UE that drains mana like really strong drain.
- [ ] 5. Sword of Vengeance this monsted also should have more hp, like 10x more hp and also drain mana.
- [ ] 6. There should be more Animated Swords that spawns much faster in the main room.
- [ ] 7. An Astral Glyph, this should have like 5x more hp.
- [ ] 8. An Astral Glyph and Last Lore Keeper should have UE that heals all swords like "mas res" for swords.
Killing the sword should be hard, on RL you have to coordinate your teammates UE at the same time to kill the swords before they get healed by the boss.
- [ ] 9. Sword of Vengeance and Animated Swords should do more dmg like (300-800dmg) and have spells similar to knight (exori, exori hur). Those monsters were just standing there and doing almost nothing :p

**Comment by kito2** [comment]
Esto lo pasare a la repo privada
