### ISSUE TITLE
Can't remove carpets from some sqm

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1066]
Can't wrap carpets from
Position(32927, 32119, 5)
Position(32928, 32117, 5)
![image](https://user-images.githubusercontent.com/46424212/54375106-b6508800-4680-11e9-97c7-cc4fa254b0ed.png)

**Comment by LastCrystal** [comment]
This fixed itself after server save
![image](https://user-images.githubusercontent.com/46424212/54413038-c1dd9680-46f4-11e9-8dc0-32e1633eba01.png)

**Comment by joseluis2g** [comment]
anyways this should me fixed
