### ISSUE TITLE
Achievement CGB Agent

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#107]
Date | 2018-12-22 04:32:09
-- | --
Player name | Salchichon
Position | 32385, 31778, 6
Description | Player said: "Achievement" Top CGB Agent is not working (archivement of squeezing gear of girlpower) FIX IT HOW DO WE ARE GOING TO GET ARCHIVEMENT POINTS FOR REWARDS?

**Comment by kito2** [comment]
Repeated.
