### ISSUE TITLE
Surprise Bag drops 3 cream cakes when it should drop 1.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1070]
Surprise Bag (Blue) drops 3 cream cakes after opening, should only drop one :p
https://gyazo.com/ba421fa2fe0a50a1edad8d23c58592b2

**Comment by Kertie** [comment]
We have to fix it.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/65469479-e5ce2180-de67-11e9-91c5-847e2bed4ffc.png)

**Comment by Kertie** [comment]
Now it's working.
Closed.
