### ISSUE TITLE
 Hive Overseer is healing 500 to 700 every turn

### ISSUE THREAD

**Issue by kingtinin** [kito2/mtibia-bounties#1072]
Player name | Azrei
-- | --
Position | 33513, 31175, 1
Description | Hive Overseer is healing 500 to 700 every turn almost, wikia says 500 to 700 infrequent, here it just spams it

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/63873049-2482d000-c9bf-11e9-875f-3977f9104e13.png)

It's working correctly.
