### ISSUE TITLE
Ghaz no message

### ISSUE THREAD

**Issue by TinSion** [kito2/mtibia-bounties#1074]
3. Before he appears, the following message is broadcast in white text to all players of the world he spawns in: "Gaz'haragoth will shatter your dreams in a barrage of nightmares!". 

https://www.tibiabosses.com/bossopedia/gazharagoth/ << need add message to ghaz appear

**Comment by joerod1** [comment]
@Kertie do you know how to test this?

**Comment by Infermus** [comment]
@joerod1 You have to iniciate Gaz'harogoth raid. I don't know what command are you using to do that. But it should be in command.cpp

**Comment by Kertie** [comment]
Kito told me that our system doesn't show these messages because, Gaz appears on server save.
So, closed.
