### ISSUE TITLE
Corpses of diremaws and deep worms are not pushable

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1075]
Date | 2019-03-16 16:16:52
-- | --
Player name | Kingtin
Position | 31909, 31441, 13
Description | **Player said:** Dead corpses of diremaws and deep worms are not movable/pushable.

**Comment by Kertie** [comment]
We have to fix it.

**Comment by joerod1** [comment]
@kito2 @joseluis2g  maybe otb thing?

**Comment by kito2** [comment]
@joerod1 sucede que el primer body debe durar aprox 5 segundos sin moverse, luego el decay ya puede moverse. Esto es asi con todos los corpses.

Habria que cambiar `<attribute key="duration" value="200" />` por `<attribute key="duration" value="5" />`.

Esto en el **primer** corpse de diremaw (id: 30789) y en el **primer** corpse de deepworm (id: 30840).

**Comment by joseluis2g** [comment]
? pero si ni un cuerpo se puede mover

**Comment by Kertie** [comment]
Sí, mira el 30789 pasa a 30790 y ese si se puede pushear.
El 30840 pasa a 30839, y al igual que el otro se puede mover.
@joerod1 @joseluis2g

**Comment by kito2** [comment]
Fijate en todos los cuerpos, cuando alguien mata a la creatura, el dueño no puede moverlo por breves segundos, y luego los demas pueden moverlo. 

Esto se hizo como un update en RL para prevenir los robos de loot.

La solucion es solo cambiar el duration de 30789 y 30840 a 5 segundos.

**Comment by Kertie** [comment]
Si, supongo que en el items.xml

**Comment by Kertie** [comment]
Now it's working.
Closed.
