### ISSUE TITLE
Unable to exchange the old cape/sedge hat for Wayfarer addon 

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1077]
Date | 2019-03-16 14:35:52
-- | --
Player name | Bullet Sponge
Position | 32930, 32072, 7
Description | **Player said:** I'm unable to exchange the old cape/sedge hat for the wayfarer outfit addons with the npc cranky lizard crone--he has no reaction for when I confirm I have the item(s) with me (I have wote/father's burden/interest in botany quests completed).

**Comment by Kertie** [comment]
This quest isn't working at all. However, I did it and I had my outfit.
Closed.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/66006009-72529280-e4ad-11e9-84e8-5afc4f9ad3b1.png)

![image](https://user-images.githubusercontent.com/45070560/66006014-7979a080-e4ad-11e9-96a0-2c5b80686e03.png)

You've to give Sedge Hat and Old Cape to this NPC.

Closed.

**Comment by joseluis2g** [comment]
well transcripts are not equal

**Comment by joseluis2g** [comment]
https://www.tibiawiki.com.br/wiki/Wayfarer_Outfits_Quest

**Comment by Kertie** [comment]
Outfits are not working in the same way as RL Tibia.
It's modified on our server.

The issue is related to be able to obtain these addons which you can obtain. So, if we want to change the way to obtain, we should open a new issue.
