### ISSUE TITLE
Perod missing Crystalline Arrow

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1079]
NPC Perod (Port Hope) doesn't sell Crystalline Arrow.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64380755-f3934280-d031-11e9-801a-6ccff289bf8e.png)

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/65729513-d98fd180-e0be-11e9-9fd7-ed6e9fc238fa.png)

Now it's working.
Closed.
