### ISSUE TITLE
Cuckoo Clock doesn't show time

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1088]
Cuckoo Clock should show you the Tibian time when being used
https://tibia.fandom.com/wiki/Cuckoo_Clock

**Comment by Kertie** [comment]
There are two IDs for this item. 
- If you create it using /i command (1881).
- If you buy it from NPCs (1877)

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64025157-5a00f800-cb3c-11e9-9600-33ae7c8c2bf4.png)

![image](https://user-images.githubusercontent.com/45070560/64025177-684f1400-cb3c-11e9-9122-26a53c25b772.png)


It's working now in both items ID.
Closed.
