### ISSUE TITLE
Glooth Factory Quest, handling glooth capsule to Elbert

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1090]
Date | 2019-03-21 00:49:51
-- | --
Player name | Niebezimienny
Position | 33627, 31898, 6
Description | **Player said:** After handling to Elbert 10 glooth capsule you should reveive 2 vote poitns, not 1. Also if you got 10 glooth capsule he will not accept that. You need have at least 11 and then he will exchange them (of course he will take 10 not 11) **Part of the Glooth Factory Quest**

**Comment by Kertie** [comment]
Attending to the code it should be fixed.
So, closed.
