### ISSUE TITLE
Ghostly Woman missing transcripts

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1093]
A Ghostly Woman (Dream Realm) is missing transcripts to exchange _leather boots_ for a hint.
RPG content not required for main quest.

**Player**: _boots_
**A Ghostly Woman:**  __Do_ you have a pair of boots for me?_
**Player:** _yes_
**A Ghostly Woman:** _Oh thank you. Perhaps this will give me some comfort. It is that cold since I am dead ... for so long ..._
**A Ghostly Woman:** _All I can give you is a little hint though: Not me but only the lost heroes can show you the way; and though it's only a game, it might change what will happen._

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/65553974-86841600-df28-11e9-89c5-b8d75daac8b6.png)

> A Ghostly Woman: Oh thank you. Perhaps this will give me some comfort. It is that cold since I am dead ... for so long ...

We have to add this sentence on transcript.

**Comment by Kertie** [comment]
It's working now.
Closed.
