### ISSUE TITLE
Dragon Essence from First Dragon Quest

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1095]
Why are those monsters healing 10k every 20 seconds? **(Dragon Essence)**
I know it should be a little harder than on RL but how someone supposed to kill them? :p
![image](https://user-images.githubusercontent.com/46424212/54969380-2531b900-4f7e-11e9-99ff-88391f346b03.png)
On RL those dragons doesn't heal like than and they should have one hp for all 6 dragon that depletes equally.
I don't think single person have done this quest on Masteria and on site there is only info about final boss being stronger not those dragons so please at least turn off this healing so it will be possible to kill them.

**Comment by joseluis2g** [comment]
wow

**Comment by joerod1** [comment]
probably we will need @kito2  here, idk which healing it could be the fair, i have been looking for some info at wikis but atm nothing found

**Comment by Kertie** [comment]
Yes, it's true. I gave this issue the 'Suggestion' label.
We would need @kito2 's oppinion in order to decide the way to act.

**Comment by kito2** [comment]
@joerod1 can you post here the link to the respective code to take a look the attributes of healing?

**Comment by joerod1** [comment]
> @joerod1 can you post here the link to the respective code to take a look the attributes of healing?

https://github.com/kito2/mtibia_master/blob/master/data/monster/11.2/Dragon%20Warden.xml

**Comment by kito2** [comment]
No tiene ningun heal por XML, debe ser por lua.

**Comment by kito2** [comment]
https://github.com/kito2/mtibia_master/blob/af4ee588b80196647d910a15eaace8bd5d769cf7/data/creaturescripts/scripts/quests/first%20dragon%20quest/firstdragon_preparedeath.lua

https://github.com/kito2/mtibia_master/blob/af4ee588b80196647d910a15eaace8bd5d769cf7/data/creaturescripts/scripts/quests/first%20dragon%20quest/firstdragon_kill.lua

https://github.com/kito2/mtibia_master/blob/af4ee588b80196647d910a15eaace8bd5d769cf7/data/lib/miscellaneous/firstDragon.lua

**Comment by kito2** [comment]
Estuve mirando esos codigos que son lo q aparece respecto al Dragon Warden y no hay nada de heal que yo haya podido percatarme.

@joseluis2g podrias mirar esos archivos tu tmb y verificar q no hayan condiciones de agregar HP?

**Comment by kito2** [comment]
Busque por heal y add, no encontre nada.

**Comment by joerod1** [comment]
@kito2 https://github.com/kito2/mtibia_master/blob/master/data/monster/dragons/dragon%20essence.xml 
la cosa es que tiene curación de entre 5k y 10k cada dos segundos con un 16% de probabilidades de ejecutarla
```
defense name="healing" interval="2000" chance="16" min="5000" max="10000">
			<attribute key="areaEffect" value="blueshimmer"/>
```

**Comment by Kertie** [comment]
[DRAGON ESSENCE.docx](https://github.com/kito2/mtibia-bounties/files/3649729/DRAGON.ESSENCE.docx)

I'm not sure if it's working.

**Comment by Kertie** [comment]
Corrected and closed.
