### ISSUE TITLE
Flint should be selling Exercise Sword/Bow/Club/Axe instead of Alaistar at Rathleon

### ISSUE THREAD

**Issue by kingtinin** [kito2/mtibia-bounties#1105]
Date | 2019-04-02 19:17:13
-- | --
Player name | Kingtin
Position | 33593, 31907, 4
Description | Flint should be selling Exercise Sword/Bow/Club/Axe instead of Alaistar at Rathleon(Oramond)

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64288606-d3e11900-cf62-11e9-9dd0-a936d0650ef4.png)

Now it's working.
Closed.
