### ISSUE TITLE
Can't summon Orc Leader

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1108]
**Utevo res "Orc Leader** doesn't work.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/63875861-a5909600-c9c4-11e9-84e7-199113929ec3.png)

Tested with ED level 80.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64025079-363db200-cb3c-11e9-953d-30f84244a621.png)

It's working properly. So, closed.
