### ISSUE TITLE
Kroazur loot container

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1116]
The loot container in dead body of Kroazur is too small, it doesn't show all the looted items. New items keeps appearing after taking out some of the loot.
![image](https://user-images.githubusercontent.com/46424212/55570076-f7c5d780-5702-11e9-8994-55d93936209e.png)
It someone doesn't look at _loot channel_ can easily miss rare items.

**Comment by joseluis2g** [comment]
Fixed

**Comment by Kertie** [comment]
@joseluis2g Did you upload it to the server?

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64076961-b5adbb80-cccb-11e9-95ad-2312f3740091.png)

It's working properly.
Closed.
