### ISSUE TITLE
Rock bug falcon bastion

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1124]
This position at left is walkable on RL
![image](https://user-images.githubusercontent.com/46424212/55855926-198ee680-5b69-11e9-94db-2883a5295151.png)
**33385,31341,5**

**Comment by Infermus** [comment]
Working @Kertie 
![image](https://user-images.githubusercontent.com/35379749/66000334-7e375800-e49f-11e9-997c-47751ba15cc3.png)

**Comment by Kertie** [comment]
So, closed.
Thanks @Infermus .
