### ISSUE TITLE
Sweetheart Ring missing animation

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1125]
When using an equipped **Sweetheart Ring**, a heart animation should play on your character but it doesn't. https://tibia.fandom.com/wiki/Hearts_Effect

**Comment by joseluis2g** [comment]
Fixed

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/58746332-7fa73400-845d-11e9-95ab-09156da174a4.png)

Closed.
