### ISSUE TITLE
Firewalker boots doesn't work on purple fire

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1126]
Firewalker boots should also work on **searing fire** (purple fire at POI gates)

**Comment by joseluis2g** [comment]
I tested and its working :P

**Comment by joseluis2g** [comment]
Fixed

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/58436698-fdb6b400-80c6-11e9-8eaa-78dd59a40d8f.png)

As @joseluis2g said, it's working now.
Closed.
