### ISSUE TITLE
Wooden Whistle doesn't spawn Wolf

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1127]
Using Wooden Whistle should spawn Wolves with 30% chance and have a 70% chance of breaking.
https://tibia.fandom.com/wiki/Wooden_Whistle

**Comment by joseluis2g** [comment]
Fixed

**Comment by Kertie** [comment]
Should I check it? @joseluis2g

**Comment by Kertie** [comment]
It isn't working right now.

![image](https://user-images.githubusercontent.com/45070560/63868065-31e78c80-c9b6-11e9-972c-deca2df30531.png)

**Comment by joerod1** [comment]
i have tested it and it's working ok, check id 5786

**Comment by Kertie** [comment]
Okey. That was my fail!
It's working.
Closed.
