### ISSUE TITLE
Cornucopia should create Grapes

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#1128]
When used, should creates 10 bunches of Grapes and plays Musical Notes.
Doesn't create grapes and has no chance of breaking.
https://tibia.fandom.com/wiki/Cornucopia

**Comment by joseluis2g** [comment]
Fixed

**Comment by Kertie** [comment]
Should I check it? @joseluis2g

**Comment by Kertie** [comment]
It's fixed.

You can broke the item and also it's showing music notes and it creates grapes.
