### ISSUE TITLE
Green mushroom too weak

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#113]
Date | 2018-12-22 16:00:52
-- | --
Player name | Sendis
Position | 32801, 31243, 7
Description | the green mushrooms are bugged, they eat alot.. its not like global (only eat 2 in global)

**Comment by joseluis2g** [comment]
green mushrooms should heal you for 60 seconds, it works as intended.
@Kertie

**Comment by Kertie** [comment]
What player reported is that you could eat more than Tibia CipSoft. However, I've seen that the player was confused.

The mushroom you can eat only 2 in global is BROWN mushroom, so the report is false.

Closed, thank you!
