### ISSUE TITLE
Free Premium on client.

### ISSUE THREAD

**Issue by Kertie** [kito2/mtibia-bounties#1131]
The message is in spanish, so we should change it into english.

![image](https://user-images.githubusercontent.com/45070560/57179018-4ccb4980-6e79-11e9-9d98-c5a87acf78c7.png)

**Comment by joseluis2g** [comment]
Actually cipsoft is a germany company and Gratis means Free there.

**Comment by Kertie** [comment]
The problem is that we show this message in spanish and most of the people who would play Masteria isn't spanish. That's why we should change "Gratis Premium Account" into "Free Premium Account".

**Comment by joseluis2g** [comment]
I dont think this is a problem, I mean its client related.

**Comment by Kertie** [comment]
Yes, it is related to client. 
I wrote it on the title.
