### ISSUE TITLE
Minor bug related to casks.

### ISSUE THREAD

**Issue by Kertie** [kito2/mtibia-bounties#1135]
You can fill small vials using a great cask. 

For example: if you have x1 sample potions (empty) and x2 great potions (empty). 

When you use the cask (sample or great, it doesn't care), you will obtain 1+2 --> 3 potions (sample or great, it depends on which cask you use)

![image](https://user-images.githubusercontent.com/45070560/58704544-b40ee780-83ac-11e9-8d50-8429b7726277.png)

![image](https://user-images.githubusercontent.com/45070560/58704584-dbfe4b00-83ac-11e9-9d37-b125e4db0016.png)

**Comment by joseluis2g** [comment]
wtf

**Comment by Kertie** [comment]
Okey, now it's working.
Closed.
