### ISSUE TITLE
Festive Outfits Quest Dialogue.

### ISSUE THREAD

**Issue by Kertie** [kito2/mtibia-bounties#1139]
![image](https://user-images.githubusercontent.com/45070560/59230832-0dfa8300-8bdf-11e9-88dd-f60cd836b1b3.png)

### **_The dialogue should be:_**

![image](https://user-images.githubusercontent.com/45070560/59230848-1f438f80-8bdf-11e9-81fa-e5daef923f67.png)

**Comment by Infermus** [comment]
Npc only reacts to word "addons". Seems like dialogue is not proper.

**Comment by Kertie** [comment]
Now it's working.
Closed.
