### ISSUE TITLE
Makeshift Warrior Outfit

### ISSUE THREAD

**Issue by Infermus** [kito2/mtibia-bounties#1143]
Plan for a Makeshift Armour (30950), Crude Wood Planks (30952), Tinged Pot (31304), those 3 items are unusable, due to this issue, player is unable to complete Makeshift Warrior Outfit.

**Comment by Kertie** [comment]
@Infermus Could you check it?

**Comment by Infermus** [comment]
![makeshift armor](https://user-images.githubusercontent.com/35379749/64944772-650f9400-d86f-11e9-8bdd-69ec404e8cb1.png)

Not working, player can't use Crude Wood Planks (30952) & Tinged Pot (31304), because getting message that he don't have basic outfit. Also those item shoudn't be able to use twice

**Comment by Kertie** [comment]
Now it's working.
![image](https://user-images.githubusercontent.com/45070560/65278615-c44dfc80-db2c-11e9-9381-9ae3fc493c85.png)

Closed.
