### ISSUE TITLE
Shaman Outfits Quest - Addons

### ISSUE THREAD

**Issue by Infermus** [kito2/mtibia-bounties#1145]
Addons for Shaman Outift Quest are not working. They are unavailable.
![staff](https://user-images.githubusercontent.com/35379749/59678755-7d6b0680-91cd-11e9-9639-56e8c8d45cf2.JPG)

After that dialogue, player still don't have staff addon.

**Comment by joseluis2g** [comment]
Whats wrong with this?
![wtf](https://i.imgur.com/OvCMGuc.png)

**Comment by Infermus** [comment]
Thats strange, I tested it with all completed pre-quests, and I wasnt able to obtain addons. Gonna take another look for this tomorrow

**Comment by joseluis2g** [comment]
you only need shaman outfit

**Comment by Infermus** [comment]
![togit](https://user-images.githubusercontent.com/35379749/59960650-945e7100-94cb-11e9-8a5d-90bccaf3edbe.JPG)

@joseluis2g

**Comment by joseluis2g** [comment]
¿?¿ I also did it on the testserver thats so weird

**Comment by Infermus** [comment]
I think this issue should be reopen. Please also add label "Need more informations". We gonna check it again and try to figure out that exactly is going on.

**Comment by joseluis2g** [comment]
can you create a new char and test?

**Comment by Infermus** [comment]
Gonna try with new character when masteria will be online again.
