### ISSUE TITLE
Bot getting stuck on monsters.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#117]
Date | 2018-12-22 20:36:37
-- | --
Player name | Tank Yusuf
Position | 31904, 31021, 10
Description | Player said: Can u fix the problem with the summons of creatures like death glob or slime and others my bot doesnt sees it as a monster and getting stuck with it

**Comment by joseluis2g** [comment]
How can I test this? Does bots not recognize summons or what.

**Comment by Kertie** [comment]
I think that it's related to his/her bot.
So, if you agree with me, we could close this issue. The main reason is that we don't know which bot he/she uses and it may be bot's failure.

**Comment by joseluis2g** [comment]
you got new info?
