### ISSUE TITLE
ice island quest

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#120]
Date | 2018-12-23 00:05:08
-- | --
Player name | Puzofugazo
Position | 32404, 32241, 11
Description | ice island quest 5. mission picking up lava from an inactive lava hole with a spoon, doesnt work in thais fire devil dungeon

**Comment by Kertie** [comment]
The report is true. You can't take 'Fine Sulphur' from inactive lava hole.
So you can't finish the quest.

**Comment by kito2** [comment]
![image](https://user-images.githubusercontent.com/21250744/64873246-0bb12600-d61f-11e9-8491-8df27fd09893.png)

**Comment by Kertie** [comment]
It's the only one that works?

**Comment by Kertie** [comment]
When you buy Nilsor's waterskin. 
00:56 You see Nilsor's waterskin.
It weighs 7.00 oz.
**It is filled with warm geyser water.**

**Comment by Kertie** [comment]
### **ISSUE TRACKING**
- [ ] Make possible to obtain Fine Sulphur from an inactive lava hole.
- [ ] To change Waterskin's message.

**Comment by Kertie** [comment]
Now it's working.
Closed.
