### ISSUE TITLE
Transcripts with nilsor on ice island

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#121]
Date | 2018-12-23 00:44:06
-- | --
Player name | Puzofugazo
Position | 32329, 31049, 7
Description | Player said: Transcripts with nilsor ice islands mission 5 when you give the items 5 of 7 items doesnt work neither with official transcripts or at all, tried everything

**Comment by joseluis2g** [comment]
Podríamos probar esto en el test server?
@Kertie

**Comment by Kertie** [comment]
Yes, I'll test the whole quest during this week.
I'll give you some feedback after testing it.

**Comment by Kertie** [comment]
Okey He acepts 'Fine Sulphur'. The problem is that this item is not obtainable on our server, since inactive lava hole doesn't give it using the knife.
