### ISSUE TITLE
Bugged coal

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#123]
Date | 2018-12-23 08:30:11
-- | --
Player name | GOD Anabelle
Position | 32699, 31492, 11
Description | Bugged coal in the wagon.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64482267-0141f700-d1ef-11e9-89f1-6b29a2e1fc48.png)

It's a false report.
Closed.
