### ISSUE TITLE
Can't use the sceptre

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#138]
Date | 2018-12-23 19:57:50
-- | --
Player name | GM Kertie
Position | 33362, 31400, 10
Description | Players can't use the sceptre

**Comment by joseluis2g** [comment]
whats is the spectre?

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/57169692-97f94400-6e08-11e9-8727-46446dc67d1f.png)

I think it's WoTE Quest. However, I think that people could use it.
I'll try contact someone in order to know if the quest was finally available.

**Comment by Kertie** [comment]
I give you more info about the item and the quest in which is involved.

https://tibia.fandom.com/wiki/Snake_Sceptre
https://tibia.fandom.com/wiki/Wrath_of_the_Emperor_Quest

![image](https://user-images.githubusercontent.com/45070560/57169883-b875ce00-6e09-11e9-9882-6324407d4150.png)

**Comment by LastCrystal** [comment]
It should work now, I remember doing it
There used to be bug with one of the bosses body, where you couldn't use it on it but I think was already fixed long time ago

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/57418205-84811b00-7204-11e9-9baa-b066ed0b53b9.png)

As @LastCrystal said it is already fixed.
Thank you.

Closed.
