### ISSUE TITLE
The Secret Service Q.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#151]
Date | 2018-12-24 21:13:48
-- | --
Player name | Your Father
Position | 32639, 32343, 6
Description | Mission: The Secret Service quest I can't open the door on Dark Catedra where a box with plans is located.

**Comment by Kertie** [comment]
There is a minor problem on mission 3.

You have to use an item on the door and a bug tral appears. The problem is that should appears x4 bug trals.

![image](https://user-images.githubusercontent.com/45070560/58285695-91c60a00-7dad-11e9-864f-96437f013221.png)

**Comment by Kertie** [comment]
The report is false.
So, closed.
