### ISSUE TITLE
Fishing from Water Elemental body

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#166]
Date | 2018-12-26 11:32:41
-- | --
Player name | GOD Anabelle
Position | 32790, 31756, 10
Description | Water Elemental: after fishing from body - the water disappears, should stay on the ground to be able to open body again

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/58423191-c62f1400-8094-11e9-8abd-2a8a60770b08.png)

![image](https://user-images.githubusercontent.com/45070560/58423264-ee1e7780-8094-11e9-8c64-f3b4c680c132.png)

You can open water elemental while the water is on the floor. So, closed.
