### ISSUE TITLE
Tasks in party.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#168]
Date | 2018-12-26 11:35:28
-- | --
Player name | GOD Anabelle
Position | 32790, 31756, 10
Description | Player said: When players are in party, it doesnt count monster to task

**Comment by joseluis2g** [comment]
can you test this?

**Comment by joseluis2g** [comment]
@Kertie

**Comment by Kertie** [comment]
Of course. I will try.

**Comment by Kertie** [comment]
It is working properly.

![image](https://user-images.githubusercontent.com/45070560/58442295-31570580-80ea-11e9-87a5-e13edfab9a64.png)

![image](https://user-images.githubusercontent.com/45070560/58442303-3f0c8b00-80ea-11e9-8550-f4de50834f74.png)

Closed.
