### ISSUE TITLE
Scammed by player

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#174]
Date | 2018-12-26 22:36:14
-- | --
Player name | Showbizz
Position | 33237, 32407, 7
Description | Player said: How is it possible that a random player can name him self as "admin masteria" and scam people. my brother named "tempest" got scammed(thiefed) from him. it is really sad. ifu want his character where he send the items and coins "John".

**Comment by Tenzhiro** [comment]
There really has to be put a filter on name choosing..

**Comment by joseluis2g** [comment]
and the player should check support section before.
