### ISSUE TITLE
Can't cancel market offer

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#175]
Date | 2018-12-26 23:07:41
-- | --
Player name | Rammus
Position | 32327, 32268, 8
Description | Player said: I have buyoffer on coins on market when i cancel it i get kicked

**Comment by Kertie** [comment]
I have just put an offer to buy coins. Then I tried to cancel it, and there is no problem.

It seems like it wasn't true or it's fixed already.

Closed.
