### ISSUE TITLE
Can't cancel buy offer.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#181]
Date | 2018-12-27 11:09:57
-- | --
Player name | Paladynski
Position | 33209, 32456, 8
Description | Player said: Hello, I can't cancel my buy offer if im trying multiple times im getting debug. Plese help

**Comment by Kertie** [comment]
I have another problem related to market.
![image](https://user-images.githubusercontent.com/45070560/64482298-99d87700-d1ef-11e9-8911-9f862ff30a08.png)

- I created my offer (same as photo)
- I cancelled that offer (I lost my money)
- I tried to create the same offer (it was impossible to create)

**Comment by Kertie** [comment]
I was able to cancel my offer.
I couldn't reproduce this 'debug'.
So, closed.
