### ISSUE TITLE
Achievement Marble Madness

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#189]
Date | 2018-12-27 21:40:02
-- | --
Player name | Elder Imbir
Position | 32648, 31911, 8
Description | Achievement Marble Madness doesn't work

**Comment by LastCrystal** [comment]
You guys fixed how obi knife works on marble rocks but there is still no achievements (Marblelous and Marble Madness) for creating beautiful marble statue.

**Comment by kito2** [comment]
Moved to private git.
