### ISSUE TITLE
No boss after necro task

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#204]
Date | 2018-12-28 09:22:22
-- | --
Player name | Sputnik
Position | 32397, 32119, 7
Description |  Player said: I killed 4k necro and talk to grizzly and cant fight boss? now I talk to Lugri and he give me new task of 4k necros.. wtf?

**Comment by kito2** [comment]
In order to kill Necropharus, must talk to Grizzly Adams. This info must be updated on website eventually.
