### ISSUE TITLE
Can't heal my summons by uh/ih

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#21]
Date | 2018-12-18 18:48:01
-- | --
Player name | Mati Kogut
Position | 32508, 31722, 15
Description | cant heal my summons by uh/ih, only with massress

**Comment by kito2** [comment]
Not reproducible, I could heal my summon with UH.

https://gyazo.com/b6253f6fda257006eb02dcb4e2f95a5d

**Comment by LastCrystal** [comment]
It was about normal summons like demon skeleton, orc berserker etc. Mas res works but you can't heal them with runes.
![image](https://user-images.githubusercontent.com/46424212/55513821-f0e98700-5666-11e9-9de2-0a84f5e69432.png)

**Comment by Kertie** [comment]
I add some information about this issue.
You waste one charge even not healing your summon.

**Comment by kito2** [comment]
This is suppose to only work on "summons 200+" not on regular summons.
