### ISSUE TITLE
Animated dead rune doesn't work

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#213]
Date | 2018-12-28 17:34:29
-- | --
Player name | Buddy
Position | 32354, 32155, 10
Description | animated dead rune does no effect on whatever corpse do you use it

**Comment by Kertie** [comment]
This report is true.

It doesn't work even using on yourself, on the body or on the floor.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64482386-2df70e00-d1f1-11e9-9296-efcccca782c8.png)
![image](https://user-images.githubusercontent.com/45070560/64482395-41a27480-d1f1-11e9-9918-c9b028467dfb.png)
![image](https://user-images.githubusercontent.com/45070560/64482399-5da61600-d1f1-11e9-8af2-f5cfbd19fa55.png)

It's working.
So, closed.
