### ISSUE TITLE
Npc mising item

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#216]
Date | 2018-12-28 20:21:38
-- | --
Player name | Unbench The Kench
Position | 33638, 31889, 5
Description | Oramond Temple NPC should sell flowers like it is on rl tibia

**Comment by LastCrystal** [comment]
Npc **Azalea** should sell:
**Exotic Flowers** - 300gp
**Flower Bowl** - 6gp
**God Flowers** - 5gp
**Honey Flower** - 5gp
**Indoor Plant Kit** - 8gp
**Potted Flower** - 5gp

**Comment by Kertie** [comment]
You can copy the trade from Rose NPC. Both are selling the same items.

**Comment by Kertie** [comment]
@joseluis2g Azalea and Rose are buying these items instead of selling them.

![image](https://user-images.githubusercontent.com/45070560/65415417-03fb3980-ddf6-11e9-9b19-8203aeb3a2a3.png)

**Comment by joseluis2g** [comment]
my bad

**Comment by Kertie** [comment]
Now it's working.
Closed.
