### ISSUE TITLE
Is frozen ursagrodon mount bugged?

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#220]
Date | 2018-12-28 23:16:29
-- | --
Player name | Sendis
Position | 32072, 30991, 8
Description | Player said: frozen ursagrodon mount is bugged, my friend tried 7x times with melting horn but still cant... i think its not like REAL tibia, because in RL first the ursagrodon get unfreeze and then use item

**Comment by Tenzhiro** [comment]
I have seen people with the mount, the mount item is supposed to break very easily

**Comment by kito2** [comment]
Not a bug.
