### ISSUE TITLE
Bug while depositing stackable items

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#232]
Date | 2018-12-29 17:23:16
-- | --
Player name | Eazy Rushdem
Position | 32346, 32219, 5
Description | Eazy said: I've noticed that there is a bug while depositing stackable items into depot, for example I had 2 Pages of items in Depot Box VIII In 2nd page I had 70 diremaw legs, and I added 40 more to this box, It added 30 to those 100, but remaining 10 disappea

**Comment by kito2** [comment]
Already reported.
