### ISSUE TITLE
Achievement Talented Dancer

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#241]
Date | 2018-12-30 11:30:41
-- | --
Player name | Mastah Abo
Position | 33005, 31489, 10
Description | No Talented Dancer achievement for completing Mission 3 of Unnatural Selection Quest.

**Comment by LastCrystal** [comment]
Player Holera said: After getting the achievement Talented Dancer (Unnatural Selection Quest) my number of achievement points decreased from 59 to 56

**Comment by kito2** [comment]
Moved to private git.
