### ISSUE TITLE
Banshee Quest

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#244]
Date | 2018-12-30 16:54:46
-- | --
Player name | GM Kertie
Position | 32318, 31934, 7
Description | I think that the bug in Banshee Quest affects to First Wizard Addon (Shoulder)

**Comment by Infermus** [comment]
22:10 Congratulations! You earned the achievement "Warlock".
![image](https://user-images.githubusercontent.com/35379749/65997242-4a593400-e499-11e9-86d4-cfa777234291.png)

Banshee's Quest is not required in Wizard Addon Quest

**Comment by Kertie** [comment]
So, closed.
Thank you @Infermus .
