### ISSUE TITLE
Reward chest at falcon

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#245]
Date | 2018-12-30 17:27:21
-- | --
Player name | Malutki Przemcio
Position | 33389, 31269, 7
Description | Player said: Reward chest at falcon bossed is opening normally instead of giving rewards.

**Comment by kito2** [comment]
Already fixed.

**Comment by Infermus** [comment]
Crystal was right, anyway still not working ;3

**Comment by kito2** [comment]
@Infermus 

Do you know which key doors do they loot? 
Which are the statistics?
-------------------------
@joerod1 can you create a script for them, they are daily chest with 20 hr delay to be used per player. So a chest can be used many times a day by different players, but you can use it again after this delay has been finished.

**Comment by Infermus** [comment]
Ye I know for which one is key that drops from one of that chests @kito2 
Its: https://tibia.fandom.com/wiki/Key_0909

Doors for open:
https://tibiopedia.pl/maps/3536/2421/6/8
https://tibiopedia.pl/maps/3543/2403/6/8

Chest that gives key:
https://tibiopedia.pl/maps/3552/2393/6/14
