### ISSUE TITLE
Can't enter boss

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#252]
Date | 2018-12-30 20:35:21
-- | --
Player name | Subranoz
Position | 32892, 31620, 10
Description | Player said: cant enter death portal boss because i throwed away the lamp in RL u have accses without lamp and key

**Comment by kito2** [comment]
It will be needed to reproduce this bug.

**Comment by LastCrystal** [comment]
On rl after slaying the boss once, you can enter boss room with just **ghostsilver lantern** but here you also need **old silver key.**
![lampaa](https://user-images.githubusercontent.com/46424212/51724624-8ad8f600-205e-11e9-91f4-ce7a5b3e3037.png)
Position(32891, 31620, 10)

**Comment by kito2** [comment]
Corrected.
