### ISSUE TITLE
Can't cancel offer

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#253]
Date | 2018-12-30 22:29:06
-- | --
Player name | Maczetka
Position | 32343, 32222, 8
Description | Player said: so, I put silver token on market for 130k and i dont have that money and I cant cancel offer, but I got this in "MY OFFERS" , same with avenger

**Comment by kito2** [comment]
This mean someone bought it.. If he closes the client and open again, relog... He will see it, it's named a cache problem of the client.
