### ISSUE TITLE
Decorations disappear from walls after ss

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#259]
Date | 2018-12-31 11:51:05
-- | --
Player name | GM Tin
Position | 32922, 32119, 6
Description | This walls on house +1 and -1 dissapear items type "trophys" etc. after server save

**Comment by LastCrystal** [comment]
https://forum.masteria.net/threads/bug-in-house.1025/

**Comment by kito2** [comment]
Already reported.
