### ISSUE TITLE
 Portal does not work

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#26]
Date | 2018-12-19 16:23:48
-- | --
Player name | Xeros
Position | 32949, 31520, 7
Description | portal does not work

**Comment by kito2** [comment]
Where does this portal takes to?

![image](https://user-images.githubusercontent.com/21250744/51134720-1e1c5b00-1817-11e9-8d1c-347115ff376f.png)

**Comment by kito2** [comment]
Eazy Rushdem: Refers to Devovorga Mini World Change 

https://tibia.fandom.com/wiki/Devovorga%27s_Essence_Mini_World_Change

**Comment by kito2** [comment]
Eazy Rushdem: Refers to Devovorga Mini World Change 

https://tibia.fandom.com/wiki/Devovorga%27s_Essence_Mini_World_Change
