### ISSUE TITLE
Boxes on deeplings

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#285]
Date | 2019-01-02 00:09:48
-- | --
Player name | Mielencin Lfc
Position | 33447, 31321, 7
Description | Player said: The boxes are not working on deepling boxes. i place the box on the sqm and i cant use shovel on it to destroy it to put the next one. after this, i checked if i can enter the tp's but i cant
Description | Malutki Przemcio said: "my task with deepling crates is not refreshed" (probably in the quest log), which means that he can not fight the bosses at all

**Comment by kito2** [comment]
Not a bug, have to wait until next day.
