### ISSUE TITLE
Oramond 500 vote missing tp

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#289]
Date | 2019-01-02 13:31:11
-- | --
Player name | Anjoh
Position | 33642, 31899, 7
Description | no tp to quest room and other hunt spawns in maxxen dungeon? Oramond 500 vote

**Comment by Tibianus** [comment]
There is missing spawn at down floors which I'm currently trying to 'remake' using youtube videos, it's almost done and should appear after tommorow's server save which is 10.01.2019
