### ISSUE TITLE
Ritual edron (falcon)

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#318]
Date | 2019-01-03 23:12:36
-- | --
Player name | GM Tin
Position | 32344, 32223, 7
Description | Ritual edron (falcon bastion) players report when u do ritual u cant repeat because dont work(test before acept bug)

**Comment by LastCrystal** [comment]
There is a problem with this ritual. Yes, the ritual works but after compliting it once you can't get any more **buckets filled with chalk**.
I tested it with multiple people here: Position(33200, 31762, 4)
![image](https://user-images.githubusercontent.com/46424212/51951175-de1ec000-2433-11e9-9ee2-d5a6032c12ca.png)
Your **bucket** stays empty and can't get refiled.
Because of that the only way to flacons is thru shortcut at Farmine.

**Comment by LastCrystal** [comment]
Also the **buckets** that you can buy from npc can not be sold on market and have different weith that on wiki. Maybe that's why the quest isn't working properly.

**Comment by kito2** [comment]
I corrected the message of "It is empty." and added a cooldown message when transforming.

**Comment by LastCrystal** [comment]
Corrected.
