### ISSUE TITLE
General store NPC at Edron, Beatrice shouldn't be able to walk on the tiles where the crates are displayed

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#33]
Date | 2018-12-20 20:23:53
-- | --
Player name | Lucius
Position | 32666, 32684, 9
Description | the General store NPC at Edron, Beatrice shouldn't be able to walk on the tiles where the crates are displayed, the lower back row. You can't taalk to her otherwise or you have to walk around.

**Comment by kito2** [comment]
Corrected.
