### ISSUE TITLE
You see a birdcage. You see a little bird inside. (Its ID is: 2976), I cannot move this thing out of house, cannot destroy it or wrap aswell

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#343]
Date | 2019-01-05 04:59:39
-- | --
Player name | Eazy Rushdem
Position | 32331, 32232, 7
Description | 05:58 You see a birdcage. You see a little bird inside. (Its ID is: 2976), I cannot move this thing out of house, cannot destroy it or wrap aswell

**Comment by kito2** [comment]
Already corrected, you can destroy using any tool or melee weapon.
