### ISSUE TITLE
deathlings spawn is not right (missing spellsingers in places), their movement speed is too slow, and also loot rate is pretty bad

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#348]
Date | 2019-01-05 15:25:18
-- | --
Player name | Trap Polskiej Mlodziezy
Position | 33124, 32851, 6
Description | deathlings spawn is not right (missing spellsingers in places), their movement speed is too slow, and also loot rate is pretty bad - https://www.youtube.com/watch?v=BCDmQFce_EU

**Comment by kito2** [comment]
Moved to personal list of bugs.
