### ISSUE TITLE
Tip! Remember to train your skills using using exercise items on training dummies near training zones. 2 times the word "Using"

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#349]
Date | 2019-01-08 22:23:00
-- | --
Player name | Tenzhiro
Position | 32436, 32365, 7
Description | Tip! Remember to train your skills using using exercise items on training dummies near training zones. 2 times the word "Using"

**Comment by kito2** [comment]
Corrected.
