### ISSUE TITLE
wote quest is bugged, my team doing it and they have like 100 monsters on screen, i have low lvl so i die fast.... tp me to Jacaa or just check it...

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#358]
Date | 2019-01-05 18:41:24
-- | --
Player name | Sprostowany Stefan
Position | 33220, 32402, 7
Description | wote quest is bugged, my team doing it and they have like 100 monsters on screen, i have low lvl so i die fast.... tp me to Jacaa or just check it...

**Comment by LastCrystal** [comment]
Player death wasn't related to bug.
