### ISSUE TITLE
You see an obsidian truncheon (Atk:50, Def:30 +2). this wepon requries lvl and prof

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#371]
Date | 2019-01-06 00:10:11
-- | --
Player name | Heroiczna
Position | 33283, 31637, 9
Description | 01:09 You see an obsidian truncheon (Atk:50, Def:30 +2). this wepon requries lvl and prof

**Comment by kito2** [comment]
Already corrected.
