### ISSUE TITLE
Wote Is bugged wont let us use the Sceptre on the dead boss

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#372]
Date | 2019-01-06 04:30:54
-- | --
Player name | Lafter Paniki
Position | 33110, 31121, 12
Description | Wote Is bugged wont let us use the Sceptre on the dead boss

**Comment by LastCrystal** [comment]
Looks like there is still some problem with wote, got a report yesterday and another one today. After using Sceptre on dead bosses body, quest log doesn't update.

**Comment by kito2** [comment]
They have to do clock wise and read error message.
