### ISSUE TITLE
why I cant ask Brewster (NPC) about the "cough syrup" in the ape city quest?

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#373]
Date | 2019-01-06 11:52:51
-- | --
Player name | Kaz Balagane
Position | 32596, 32748, 7
Description | why I cant ask Brewster (NPC) about the "cough syrup" in the ape city quest?

**Comment by Nahanti** [comment]
https://tibia.fandom.com/wiki/Flask_of_Cough_Syrup
