### ISSUE TITLE
I made Children of Revolution, Banuta Shortcut, The Ape City, Wrath of Emperor Quests but on website it shows like I didn't do it.

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#382]
Date | 2019-01-06 18:54:49
-- | --
Player name | Jan Pedofil Drugi
Position | 32249, 31099, 4
Description | I made Children of Revolution, Banuta Shortcut, The Ape City, Wrath of Emperor Quests but on website it shows like I didn't do it.

**Comment by kito2** [comment]
Moved to private git.
