### ISSUE TITLE
why mortal combat doesnt work? there is nobody inside and I got message that arena is already in use...

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#383]
Date | 2019-01-06 14:35:07
-- | --
Player name | GM Tin
Position | 32350, 32222, 7
Description | 4 Dfssdf [196]: why mortal combat doesnt work? there is nobody inside and I got message that arena is already in use...

**Comment by Nahanti** [comment]
Probably fixed.
