### ISSUE TITLE
cant talk to bron and give him fighting spirit? Bugged barbarian addon

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#385]
Date | 2019-01-08 19:15:47
-- | --
Player name | Kg At Jekab
Position | 32365, 31629, 7
Description | cant talk to bron and give him fighting spirit? Bugged barbarian addon

**Comment by Nahanti** [comment]
We need more informations, player is offline, please ask him when be back.

**Comment by kito2** [comment]
I already corrected this yesterday and applied to host, closed.

**Comment by kito2** [comment]
https://forum.masteria.net/threads/barbarian-wig-bug-got-axe-first-in-some-weird-way-and-now-wig-doesnt-work.1178/#post-8898

Not fixed properly:

-------------------------------
Ok, the patch didn't work.

Please help me here, provide me:
Your character name.
A screenshot of what Bron says when you try to interact with him on all possible dialogs trough the guide you are following and trough this guide https://tibia.fandom.com/wiki/Barbarian_Outfits_Quest/Spoiler
After having lunch I will review this again.

----------------------------------------

Absolutely! Character name "Kg at Jekab"

Gyazo of every possible dialogue/transcript with NPC BRON: 

1st gyazo: SC off dialogue with NPC bron : https://gyazo.com/a51b9fedd2a921f0cc30a72c54e99aa4
2nd gyazo: SC of whole screen to prove i got every item needed for the wig, and that i in some weird way got the axe part of the addon : https://gyazo.com/b6018ca4773c9b3a61ad96aeee111849

----------------------

Correction in progress...

**Comment by kito2** [comment]
Corrected: Copied the same stage of the player.

![image](https://user-images.githubusercontent.com/21250744/50993274-00d64c80-14f8-11e9-87a2-db6aa33ee5c9.png)
