### ISSUE TITLE
cant enter tp room of The Many, Grizzly Adams quest

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#388]
Date | 2019-01-08 00:31:29
-- | --
Player name | Joker
Position | 32919, 32875, 8
Description | I exchanged my task points for enter to boss. 2 task points = boss The Many. When im going to tp i cant enter. When back to Grizly and want to take this boss task again its not possible "You can have only 1 active task". Dont have it in quest log etc

**Comment by kito2** [comment]
False and repeated.
