### ISSUE TITLE
Orcs Raid in Thais didn't start

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#39]
Date | 2018-12-20 23:22:06
-- | --
Player name | GM Tin
Position | 32350, 32223, 7
Description | Orcs Raid in Thais didn't start

**Comment by kito2** [comment]
False report:

![image](https://user-images.githubusercontent.com/21250744/51136026-3e014e00-181a-11e9-8d37-4e0846dfac5c.png)
