### ISSUE TITLE
No-logout zone on Deepling bosses

### ISSUE THREAD

**Issue by Tibianus** [kito2/mtibia-bounties#391]
Players reported me, that some players are logging out in Deepling bosses zone then login and their time is being 'stoped' by that bug, they may kill these bosses as many as they want to. We have to add non-logout zone for Deepling bosses to prevent such situations. Also, as far as I remember, player are even able to get out from teleport, logout and then login and get in to the teleport - I think that getting out from boss zone should instantly make you not possible to join boss room again.

**Comment by kito2** [comment]
Already corrected.
