### ISSUE TITLE
Intricate Precision imbu

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#394]
Date | 2019-01-05 18:16:18
-- | --
Player name | Dywersant
Position | 32346, 32219, 7
Description | Intricate Precision - Require: 20 elven hoofs but you need 25.

**Comment by kito2** [comment]
![image](https://user-images.githubusercontent.com/21250744/51585983-3b59c500-1eba-11e9-8583-b367b8220011.png)

Not a bug.

**Comment by LastCrystal** [comment]
@kito2 Can you please look at **Elven Hoofs** again cuz on masteria you need 25 but on wiki is 20.

**Comment by LastCrystal** [comment]
Fixed.
