### ISSUE TITLE
-2 mlvl imbu bug 

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#395]
Date | 2019-01-05 22:14:08
-- | --
Player name | Jan Pedofil Drugi
Position | 32344, 32222, 7
Description | My imbue for +2 mlvl on yalahar mask ended and when I put mask to bp I got 102 mlvl. My main mlvl is 104 without items xD but it shows that I have 104-2 mlvls

**Comment by kito2** [comment]
Please post here results.

**Comment by LastCrystal** [comment]
Player told me it was only visual bug and disappear after relog. Can't reproduce it either.
