### ISSUE TITLE
Fire portal

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#396]
Date | 2019-01-06 00:06:43
-- | --
Player name | Arnold
Position | 32336, 32092, 7
Description | <01:02 Albinius: Excellente question! You just finish The New Frontier Quest, doing Mortal Combat and you will be able to enter the teleport. Albinius will not give me access to fire portal,  and I just did mortal kombat

**Comment by LastCrystal** [comment]
You need to talki with npc Ivalisse (hi/father/yes/yes) in order to enter fire portl. Just change npc Albinius response.

**Comment by kito2** [comment]
Not a bug, closed.
