### ISSUE TITLE
Wrong item weights

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#397]
Pillow Backpack weight is 18.00 oz, should be 14.50 oz.
Bronze amulet weight is 15.00 oz, should be 5.00 oz.
Elven amulet weight is 9.70 oz, should be 2.70 oz.
Kitchen knife weight is 21.00 oz, should be 1.00 oz.
Party trumpet weight is 5.00 oz, should be 0.50 oz. + item doesn't work
Present is 25.00 oz, should be 6.00 oz.
Wooden spoon is 21.00 oz, should be 1.00 oz.
Cleaver is 16.60 oz, should be 6.60 oz.
Fork is 11.00 oz, should be 1.00 oz.
Rolling pin is 15.00 oz, should be 5.00 oz
Plate is 15.00 oz, shiuld be 1.50 oz.
Spoon is 21.00 oz, should be 1.00 oz.
Very Noble-Looking Watch is 5.00 oz, should be 0.50 oz.
Item 'party hat' has no weight at all, should have 7.50 oz

**Comment by kito2** [comment]
Moved to personal bugs to correct.
