### ISSUE TITLE
Forgotten knowledge last boss

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#408]
Date | 2019-01-08 00:46:44
-- | --
Player name | Trewq
Position | 32515, 32865, 15
Description | last boss of the forgotten knowledge quest is bugged

**Comment by LastCrystal** [comment]
I think the timer after killing 4 mini bosses is bugged.
Player **Jan Pedofil Drugi** posted cam from this fight **2019-01-28 19:58:57** and they were doing everything correctly and got kicked relly fast. You can see that they killed all 4 mini bosses correctly and got kicked in less than 30 seconds.
He also made post on forum and upload video to youtube.
https://forum.masteria.net/threads/final-thais-boss-bug-the-last-lore-keeper.1779/#post-13462

**Comment by kito2** [comment]
Written into private git.
