### ISSUE TITLE
Debugs at Edron hero fortress

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#418]
Date | 2019-01-09 04:34:20
-- | --
Player name | Brabus Amg
Position | 33175, 31765, 6
Description | Player said: Continuious debugs & client crashes in Edron's hero fortress. Unfortunately i dont have any more information other than i've died numerous times due to this..

**Comment by kito2** [comment]
Probably this was due to the use of bot with HUD.
