### ISSUE TITLE
Red walls have to be fixed. It's possible to pass through them

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#42]
Date | 2018-12-20 23:25:02
-- | --
Player name | GM Tin
Position | 32350, 32223, 7
Description | Werewolves Cave. Red walls have to be fixed. It's possible to pass through them. (33115, 31941, 8)

**Comment by LastCrystal** [comment]
I posted all bugged positions here https://forum.masteria.net/threads/bug-on-grimvale.995/

**Comment by kito2** [comment]
Already reported.
