### ISSUE TITLE
Royal rescue mission

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#423]
Date | 2019-01-09 13:14:35
-- | --
Player name | Freaky
Position | 32570, 31507, 9
Description | Player said: After finished quest "the hidden city of beregar" I took quest at Emperor Rehal "royal rescue ". Next I went to the room with book and I took it and I came repair tracks. Spoiler shows that first of all I have to use "hammer" but there's no reaction.

**Comment by Kertie** [comment]
This quest is working properly.

Closed.
