### ISSUE TITLE
Island troll loot ties

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#424]
Date | 2019-01-09 13:29:26
-- | --
Player name | Avi
Position | 32295, 31798, 7
Description | island troll should loot wood, not ties.

**Comment by Kertie** [comment]
This report should not have the 'Loot Rate' label.
This label will be used for High / Low Loot Rate.

Thank you anyway for your job.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64078219-10e5ab00-ccd8-11e9-8e3a-34e40be33dc6.png)


Now it's working.
Closed.
