### ISSUE TITLE
Position shouldn't be walkable.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#43]
Date | 2018-12-20 01:25:13
-- | --
Player name | GM Kertie
Position | 33191, 31953, 8
Description | 02:24 Your current position is: Position(33191, 31951, 8) 02:24 Your current position is: Position(33191, 31952, 8) 02:24 Your current position is: Position(33191, 31953, 8) <-- Shouldn't be walkables.

**Comment by kito2** [comment]
Already corrected.
