### ISSUE TITLE
Iyad does not buy Pair of Earmuffs

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#431]
Date | 2019-01-09 16:54:59
-- | --
Player name | Woocash
Position | 32344, 32226, 5
Description | Iyad does not buy Pair of Earmuffs

**Comment by Kertie** [comment]
I tested it and doesn't work. We have to fix it.

**Comment by Kertie** [comment]
Not working. I guess that doesn't exist trade on this NPC in MTibia. So, even having a trade list, if you don't create Trade for this NPC, you are not able to sell or buy anything.

It should work saying Hi > Trade.

**Comment by Kertie** [comment]
https://i.imgur.com/gihLMWw.png

**Comment by Kertie** [comment]
Now it's working.
Closed.
