### ISSUE TITLE
Knight Legs on rookard

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#445]
Date | 2019-01-09 23:28:42
-- | --
Player name | Typowy Janusz
Position | 32098, 32197, 7
Description | Player said: 00:28 You see knight legs (Arm:8). It can only be wielded properly by knights and paladins. It weighs 70.00 oz. NPC Value: 5,000 gold coins, I cant use this iten on rookard :( please repair

**Comment by kito2** [comment]
Already fixed.
