### ISSUE TITLE
Incredibly old witch broken again

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#448]
Date | 2019-01-10 10:52:34
-- | --
Player name | GM Tin
Position | 32268, 32369, 7
Description | incredibly old witch dont make ilusion of donkey please fix since ot is opened this bug still

**Comment by LastCrystal** [comment]
I know you guys fix this cuz I got the mount some time ago, but I checked it again after ss (12th Jan) and looks like it broke again

**Comment by kito2** [comment]
Already corrected.
