### ISSUE TITLE
Quests update on the site

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#458]
Date | 2019-01-10 11:46:38
-- | --
Player name | GM Kertie
Position | 32318, 31934, 7
Description | Director said: I did annihilator quest long time ago but on the site it still doesn't show. Achievement show properly now.
Description | Player Waszka Gie said: few quest like yalahar , ice island , formogar mines , banshee quest , yalahar quarters = i have it done and on page show i did not finish
Description | Player Director said: On the website if u search my character, it doesnt show that i made annihilator and yalahar quest. Also there are 'two versions of rashid quest' in Quests Page: Travelling Traders (Rashid) and Rashid

**Comment by kito2** [comment]
Arealdy reported.
