### ISSUE TITLE
Can't enter flacons

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#465]
Date | 2019-01-10 12:40:24
-- | --
Player name | GM Kertie
Position | 33197, 31838, 7
Description | Ragnarr Lodbrok said: I am using what i should to enter falcons. 07:00 You see an item of type 31480. I can't enter flacons, idk why. Time is in between 45 & 15 so tp sould be open.

**Comment by kito2** [comment]
It doesn't require timer.
