### ISSUE TITLE
Market doesn't recognize some glooth items

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#47]
Date | 2018-12-20 23:26:15
-- | --
Player name | GM Tin
Position | 32350, 32223, 7
Description | Market doesn't recognize some glooth items (axe, club, sword, etc) even if they are brand new.

**Comment by kito2** [comment]
How to reproduce bug: https://gyazo.com/a6b3b85ba53134030fc6cc56a75b4c66

**Comment by LastCrystal** [comment]
Fixed.
