### ISSUE TITLE
Stamina regen

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#481]
Date | 2019-01-10 16:09:20
-- | --
Player name | Zagonetka
Position | 33163, 31803, 8
Description | Hey, I've been hunting for my whole happy hour ( means 2hours of xp boost while I have premium) and I logged off for like 10 hours and It only got 1 hour stamina refilled? My friend are having the same problem. Hope you can fix that!

**Comment by kito2** [comment]
It is not a bug, regeneration is the same as RL.

On orange stamina needs 3 minutes off refill 1 stamina minute.
On green stamina needs 10 minutes off to refill 1 stamina minute.
