### ISSUE TITLE
Reusable items.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#483]
Date | 2019-01-10 17:28:06
-- | --
Player name | GM Tin
Position | 32921, 32111, 6
Description | when softs decay on worn (only when decay on equip ) and you re equip another new softs it dont work (for boters it sux because need unequip x2) same happen on firewalker and werefwolf amulet.

**Comment by LastCrystal** [comment]
https://forum.masteria.net/threads/reusable-items.1208/

**Comment by kito2** [comment]
This has been writen on private git, closed for now.
