### ISSUE TITLE
Missions in Bigfoot's Burden Quest (can't report)

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#491]
Date | 2019-01-10 21:06:51
-- | --
Player name | Salice
Position | 32804, 31796, 10
Description | it is not possible to do the spark mission in bigfoot burden

**Comment by LastCrystal** [comment]
Doing test for Bigfoot's Burden Quest, second npc (Gnomespector) doesn't answer. Skiping the test and doing missions at npc (Commander Stone), he gives you quest items and it updated in questlog but after completing it you can't report. Tasks spark and keeper.

**Comment by kito2** [comment]
Moved to private git.
