### ISSUE TITLE
not working Achievements - "The Cake's the Truth" "With a Cherry on Top" "Make a Wish" "Cookie Monster" and with treasure map

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#495]
Date | 2019-01-11 07:28:47
-- | --
Player name | Blain Boltier
Position | 32400, 31815, 6
Description | not working Achievements - "The Cake's the Truth" "With a Cherry on Top" "Make a Wish" "Cookie Monster" and with treasure map

**Comment by LastCrystal** [comment]
Already reported.
