### ISSUE TITLE
There is a bug in Kalyassaa (First Dragon Quest)

### ISSUE THREAD

**Issue by AviVuitton** [kito2/mtibia-bounties#498]
Date | 2019-01-11 16:16:38
-- | --
Player name | GM Kertie
Position | 33431, 31265, 11
Description | There is a bug in Kalyassaa (First Dragon Quest) There was a guy who died in the boss, then 25~30 minutes after it, a guy who wants to enter couldn't enter, because system didn't detect that the first one die.

**Comment by kito2** [comment]
Already reported.
