### ISSUE TITLE
activating werewolf amulet through moonlight crystal; when equipped no time decay

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#504]
Date | 2019-01-11 16:48:42
-- | --
Player name | GM Kertie
Position | 33420, 31257, 11
Description | Director said: I'm not sure how this bug works, but after activating werewolf amulet through moonlight crystal when it is put on it does not count down the time later. The time is brand-new

**Comment by LastCrystal** [comment]
Kito said that this has been written on private git.
