### ISSUE TITLE
Map Bug.

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#51]
Date | 2018-12-21 01:45:10
-- | --
Player name | GM Kertie
Position | 33090, 32847, 7
Description | Map Bug.

**Comment by kito2** [comment]
When you walk up, it's move you down. Not sure how to correct: https://gyazo.com/f7ada170b6b5a5ac3c75ac6886375c9b

**Comment by kito2** [comment]
Corrected: https://gyazo.com/04ee7f1daf52474db51e604131440a67
