### ISSUE TITLE
Can't fight boss after pirate task

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#516]
Date | 2019-01-11 17:38:37
-- | --
Player name | Mayor
Position | 31977, 32857, 3
Description | Player claims, that after killing 3k pirates and reporting to Grizzly Admas he can't fight the boss.

**Comment by kito2** [comment]
It's needed a quest to proceed and have pirate set equipped.

**Comment by kito2** [comment]
Probably pirate outfit too.

**Comment by Kertie** [comment]
I think that you have to complete x3 Pirate Task (9.000 pirates)
Then you have to complete it again in order to kill the bosses.

**Comment by Kertie** [comment]
Okey. Once you finish the task, you have access to kill a boss.
Second time you finish the task, you hace acces to kill another boss.

That's the way in which it's working.

So, closed.
