### ISSUE TITLE
Fairy Teasing achievement.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#523]
Date | 2019-01-12 11:21:06
-- | --
Player name | Freaky
Position | 33476, 32198, 7
Description | Player said: it isnt possible click "dancing fairy" to achievment

**Comment by LastCrystal** [comment]
This achievement isn't even listed on server site.

**Comment by kito2** [comment]
How do you get it?

**Comment by LastCrystal** [comment]
"Fairy Teasing" - Make 100 Dancing Fairies disappear by using them

**Comment by Puchaczowsky** [comment]
I forgot add info about 100 times xDD

**Comment by kito2** [comment]
Moved to private git.

Thanks guys.
