### ISSUE TITLE
Safe spot in oramond

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#526]
Date | 2019-01-12 19:23:45
-- | --
Player name | Shordoeximondiandos
Position | 33515, 32362, 6
Description | Player said: safe spot in oramond is bugged cuz they attack trough wall and killed me wtf is this i lost 800k bounty on my head and died

**Comment by kito2** [comment]
We need more information about the dead or something else.

@LastCrystal can you help or someone else?

**Comment by kito2** [comment]
Please contact the player in game and ask more details about this bug.

**Comment by kito2** [comment]
Please post here results.

**Comment by LastCrystal** [comment]
Player sold this character and now there is a new owner. I asked him to public cams from 11th and 12th but he's only able to post cams from after he bought this character.
If the position on report is wrong, I have no ide where is this spot.

**Comment by LastCrystal** [comment]
I finally found this spot
Missing pz in Oramond temple **Position(33597, 31902, 6)**
![image](https://user-images.githubusercontent.com/46424212/53307964-bf2e1500-389d-11e9-967b-1cab94f9ef2d.png)

**Comment by kito2** [comment]
Fixed.
