### ISSUE TITLE
Rookgard pvp arena

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#527]
Date | 2019-01-12 21:01:41
-- | --
Player name | Anjoh
Position | 32955, 32023, 6
Description | I think you should add a rookgard pvp arena, where its 7.4 play style and you become to voc you are. would be sick :D also when death you dont loose anything and the map could be thais or something. Imagine the possibilities of people coming to maste

**Comment by kito2** [comment]
Moved to Suggestion at Rook Forums.
