### ISSUE TITLE
Bonus prey rerolls disappear

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#528]
Date | 2019-01-12 21:10:01
-- | --
Player name | Miinavand
Position | 32347, 32818, 6
Description | Player said: 21:08 You have claimed 4 bonus rerolls on 2 day streak., it delated all my rerolls what i just bought 24 of them
Description | Player Lapa Gopanz said: My prey rerolls just went from 100 to 0 LOL
Description | Player Voz De Galinha said: I was looking my prey system, looking the time to free roll the monsters, then i note that i lost my bonus reroll .. and a couple of hours ago i saw my bonus reroll there.. i didnt activate because i hadnt none good monster

**Comment by LastCrystal** [comment]
I noticed that after collecting bonus rerolls from reward shrine, your other rerolls disappear but it's only visual bug, after using them your other rerolls are back.

**Comment by kito2** [comment]
Moved to private git.
