### ISSUE TITLE
 Votes are bugged. There is not possibility to choose Minos or Golems.

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#54]
Date | 2018-12-21 14:51:49
-- | --
Player name | Trap Polskiej Mlodziezy
Position | 33663, 31881, 5
Description | Votes are bugged. There is not possibility to choose Minos or Golems.

**Comment by kito2** [comment]
This is not a bug, is intended to be like this, to not close the respawn of Catacombs.
