### ISSUE TITLE
Missing monsters

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#542]
Date | 2019-01-13 23:08:51
-- | --
Player name | GM Kertie
Position | 33498, 31967, 13
Description | To Nie Essa: there is a bug. NO monsters here.

**Comment by kito2** [comment]
@Kertie when you verify this.... It's not a bug.

![image](https://user-images.githubusercontent.com/21250744/51583413-317e9480-1eaf-11e9-9fa2-675ee2fb737e.png)

**Comment by Kertie** [comment]
When I went to the place, there weren't monsters.
Also Tin see that with me.

**Comment by kito2** [comment]
Is a raid which activates on time....
