### ISSUE TITLE
Falcon Bastion shotcurt Farmine

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#547]
FAQ - ''To enable the shotcurt trough Farmine, you will need to walk by at the boat at Falcon Bastion.'' I was at farmine boat 250 lvl and I can use it without any missions.

**Comment by kito2** [comment]
Just need to enter trough the ritual, kill the first bosses and step by the boat to enable it.

**Comment by LastCrystal** [comment]
@kito2 But you **can** use the Farmine shortcut **without** doing any missions or even going Edron. Which shouldn't be possible. :)

**Comment by kito2** [comment]
Uhmm ok, moved to my personal to-do list.
