### ISSUE TITLE
Task necro counts other monters.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#55]
Date | 2018-12-20 13:47:59
-- | --
Player name | Turtle
Position | 33272, 32470, 7
Description | Feyrist Isle monsters counts into Necromancer Task

**Comment by kito2** [comment]
Killed all creatures on Feyrist, and couldn't reproduce the bug:

![image](https://user-images.githubusercontent.com/21250744/51138293-84a57700-181f-11e9-8bed-01573fb2d4ac.png)
