### ISSUE TITLE
Points for The Many at Grizzlt Admas

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#555]
Date | 2019-01-15 17:56:40
-- | --
Player name | Joker
Position | 33562, 31559, 8
Description | Player said: When do u repair boss points from Adams? I took The Many and cant enter....

**Comment by kito2** [comment]
![image](https://user-images.githubusercontent.com/21250744/51582499-1447c700-1eab-11e9-8313-890a8a6c6487.png)

Not a bug.
