### ISSUE TITLE
fireball rune shot only on 1 sqm

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#576]
Date | 2019-01-16 12:40:57
-- | --
Player name | Brexumil
Position | 33269, 32593, 8
Description | fireball rune shot only on 1 sqm, should be like here:

https://vignette.wikia.nocookie.net/tibia/images/e/e7/Fireball1.gif/revision/latest?cb=20070829180448&path-prefix=en

**Comment by Petosss** [comment]
Fireball rune shot on 1sqm, its normal on tibia 10+
