### ISSUE TITLE
achievement after use small ench emerald on dracoyle statue, name of achievement: I Like it Fancy

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#577]
Date | 2019-01-17 14:01:30
-- | --
Player name | Laczkii Pijaczki
Position | 33021, 32056, 7
Description | i dont have chievement after use small ench emerald on dracoyle statue, name of achievement: I Like it Fancy

**Comment by kito2** [comment]
Moved to private git.
