### ISSUE TITLE
kissing the pig achievement -1 point

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#578]
Date | 2019-01-17 14:31:13
-- | --
Player name | Ilililililililiillililill
Position | 32432, 32224, 7
Description | kissing the pig achievement (50 piggy banks) is not working, lost/subtracts  1 achievement point :'<

**Comment by LastCrystal** [comment]
Tested achievement Allowance Collector, obtainable by breaking 50 Piggy Banks. Works fine and gives 2 points, same as wiki.
