### ISSUE TITLE
Rashid message is bad.

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#58]
Date | 2018-12-29 00:15:05
-- | --
Player name | GM Kertie
Position | 32318, 31934, 7
Description | Rashid message is bad.

**Comment by LastCrystal** [comment]
Rashid message on login will be shown properly depending on the day and current hour, based on relocation due to server save.

**Comment by LastCrystal** [comment]
Since the npc change his position after server save, this message should also only change after server save, not after 00:00 cuz it confuses a lot of players and there are a lot of questions on help channel after midnight asking where is Rashid becaus server message shows wrong location.

**Comment by joerod1** [comment]
i did something

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/57975772-708da400-79d0-11e9-8762-bca6a22db9eb.png)

It isn't working yet.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64928625-38319180-d81b-11e9-8daf-039ed308355d.png)

**Comment by Kertie** [comment]
Closed.
