### ISSUE TITLE
To weak monsters from Lower Roshamuul

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#581]
Date | 2019-01-16 19:20:40
-- | --
Player name | Puchacz
Position | 33572, 32367, 7
Description | low dmg from Lower Roshamuul monsters. 250 EK can take 8 monsters without SIO

**Comment by kito2** [comment]
I have increased the damages for about 20-30% mostly on Frazzlemaw, Silencer and Guzzlemaw. This patch will be applied after server save.

There was a report here too: https://forum.masteria.net/forums/reports.45/

Lets track the feedback of players trough the forum.
