### ISSUE TITLE
all mounts should give achievements

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#591]
Date | 2019-01-14 00:53:20
-- | --
Player name | No Tak
Position | 32301, 32462, 3
Description | all mounts should give achievements

**Comment by kito2** [comment]
@DymekPL we know this, but we need to be more specific, since we are missing all of this:

- Undead cave bear
- Tin lizzard
- Draptor
- Black sheep
- Sandstone scorpion
- Donkey
- Enraged white deer
- Uniwheel
- Wild horse
- Ironblight
- Dragonling
- Modified gnarlhound
- Shock head
- Noble lion

**Comment by kito2** [comment]
-[ ] **Knock on Wood** = Taming a Tin lizzard
-[ ] **Scales and Tail** = Taming a Draptor
-[ ] **Golden Sands** = Taming a Sandstone scorpion
-[ ] **Stuntman** = Taming a Uniwheel
-[ ] **Lucky Horseshoe** = Taming a Wild horse
-[ ] **Magnetised** = Taming a Ironblight
-[ ] **Dragon Mimicry** = Taming a Dragonling
-[ ] **Mind the Dog** = Taming a Modified gnarlhound
-[ ] **Personal Nightmare** = Taming a Shock head
-[ ] **Lion King** = Taming a Noble lion

Moved to private git.

**Comment by LastCrystal** [comment]
ach: Out of the Stone Age - Undead cave bear       
ach: Knock on Wood - Tin lizzard                 
ach: Scales and Tail - Draptor                        
ach: Little Ball of Wool - Black sheep
ach: Golden Sands - Sandstone scorpion
ach: Loyal Lad- Donkey
ach: Friend of Elves - Enraged white deer
ach: Stuntman- Uniwheel
ach: Lucky Horseshoe - Wild horse
ach: Magnetised- Ironblight
ach: Dragon Mimicry - Dragonling
ach: Mind the Dog - Modified gnarlhound
ach: Personal Nightmare - Shock head
ach: Lion King - Noble lion
