### ISSUE TITLE
Seacrest Serpents to strong?

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#593]
Date | 2019-01-17 17:37:46
-- | --
Player name | Prawiczek Tankiero
Position | 33559, 31754, 14
Description | Are Seacrest Serpents better than earlier? I did full afk lvl165 ek and I exp here till 200lvl without any dead. Today I decided to exp here again and every time I meet 3 seacrest serpent I'm instant dead(with better eq, higher lvl etc) Please check

**Comment by kito2** [comment]
No modifications have done on them.
