### ISSUE TITLE
All channels should have required 30 lvl

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#599]
Date | 2019-01-17 19:51:48
-- | --
Player name | GM Dymek
Position | 32317, 31942, 7
Description | All channels should have required 30 lvl.

**Comment by kito2** [comment]
@DymekPL why is this, much spamm on channels?

**Comment by DymekPL** [comment]
Yes. Many players make accounts and chars only for spam or trolling.

**Comment by kito2** [comment]
Changed for next patch.
