### ISSUE TITLE
Black Bert missing Post Horn

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#603]
Date | 2019-01-14 17:46:09
-- | --
Player name | Paah
Position | 32336, 32206, 6
Description | Waldo's Post Horn missing from black bert

**Comment by LastCrystal** [comment]
Also Morik's Helmet and Dark Sun Catcher.

**Comment by Nahanti** [comment]
Added but only to Black Bert, https://tibia.fandom.com/wiki/Waldo%27s_Post_Horn
