### ISSUE TITLE
Life leech does not work properly

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#607]
Date | 2019-01-15 20:37:22
-- | --
Player name | Director
Position | 32458, 32067, 7
Description | Player said: Life leech does not work properly. My friend has 50% life leech and he is playing EK. Exori heals him as intended but Exori Gran heals him for like 25% of dmg done or even less sometimes.

**Comment by kito2** [comment]
It has dereasing perfomance on AOE damage, which means reduce the total healing when damaging huge number of creatures, just like RL.
