### ISSUE TITLE
Teleport on minotaurs

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#608]
Date | 2019-01-16 00:37:44
-- | --
Player name | Growlin
Position | 32330, 32067, 15
Description | Player said: Teleport on minotaurs cults thais doesnt work - should tp back at the begginning

**Comment by kito2** [comment]
![image](https://user-images.githubusercontent.com/21250744/51582727-25dd9e80-1eac-11e9-89fa-bb1792e8ca8b.png)

@LastCrystal are you sure? I think it takes you to boss room.

**Comment by kito2** [comment]
Please post here results.

**Comment by LastCrystal** [comment]
I also think it should tp to boss room but will chcek it again later and post more info

**Comment by LastCrystal** [comment]
I check cams from rl and this tp should lead to boss room **The False God**. But it doesn't work anyways
![mino boss](https://user-images.githubusercontent.com/46424212/51744704-ed52e600-20a0-11e9-80f1-9672f25af14d.png)

**Comment by kito2** [comment]
Ok, so it's not a bug for now.
