### ISSUE TITLE
Debug darashia skeleton warrior cave + monster stats 

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#61]
Date | 2018-12-30 17:39:13
-- | --
Player name | Anjoh
Position | 33205, 32465, 8
Description | Debug darashia skeleton warrior cave, also check their hitpower and see if accurate, they hit over 900 each hit. ty :)

**Comment by Kertie** [comment]
https://www.masteria.net/community/cams/add/1760927

Let's put every cam we could in order to investigate it.

**Comment by joerod1** [comment]
haven't found the reason about debug, but about stats: https://www.tibiawiki.com.br/wiki/Skeleton_Elite_Warrior

**Comment by joerod1** [comment]
i did something

**Comment by Kertie** [comment]
About statistics, it's working now.
I'll close this issue. Let's see if debugs persist on the next season.
