### ISSUE TITLE
Player claims, that him stamina don't regen

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#612]
Date | 2019-01-16 08:48:50
-- | --
Player name | Challenger Plays
Position | 32352, 32226, 7
Description | Player said: I was offline for 10+ hours and my stamina didn't regen at all. Happened to me 2 times already, can someone please look in to this?

**Comment by kito2** [comment]
10 hours = 1 hour refill of green stamina. It wont refill at all. It uses the same formula as RL.

Closed.
