### ISSUE TITLE
achievement bug - obtaining outfits

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#614]
I didn't recived achievments for:
Full Oriental outfit
Full Pirate outfit
Full Beregar outfit
White deer mount
Donkey mount
Winning lottery ticket is bugged, cant give it to npc to recive addon.

Name: Stasiuhere
https://forum.masteria.net/threads/bug-achievments.1421/

**Comment by LastCrystal** [comment]
Oriental outfit - ach: One Thousand and One
Full Pirate outfit - ach: Swashbuckler
Full Beregar outfit - ach: Life on the Streets

**Comment by kito2** [comment]
I didn't recived achievments for:
Full Oriental outfit > One Thousand and One
Full Pirate outfit > Swashbuckler
Full Beregar outfit
White deer mount > Friend of Elves
Donkey mount > Loyal Lad
Winning lottery ticket is bugged, cant give it to npc to recive addon. > Doesn't exist

Name: Stasiuhere
https://forum.masteria.net/threads/bug-achievments.1421/

**Comment by kito2** [comment]
Moved to private git.
