### ISSUE TITLE
Collar of green plasma and ring of green plasma 60min.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#629]
Collar of green plasma and ring of green plasma have 60min timer but should have only 30min.

**Comment by kito2** [comment]
Corrected.

**Comment by LastCrystal** [comment]
@kito2 You corrected amulet but **ring of green plasma** still had 60 min times, should have 30 min.
https://gyazo.com/b9e351df4ca08cf5755bee7c646cdaa4

**Comment by kito2** [comment]
Corrected for next patch.
