### ISSUE TITLE
 workers dont drop gear crystal

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#63]
Date | 2019-01-05 20:15:01
-- | --
Player name | Hubert Elder Druid
Position | 32897, 31310, 9
Description | lol wtf, on this ot workers dont drop gear crysta

**Comment by joerod1** [comment]
i did something

**Comment by Kertie** [comment]
[Loot.txt](https://github.com/kito2/mtibia-bounties/files/3194111/Loot.txt)

**Comment by joseluis2g** [comment]
15:41 Loot of a worker golem: 68 gold coins, a gear crystal
