### ISSUE TITLE
tower shield 

### ISSUE THREAD

**Issue by Petosss** [kito2/mtibia-bounties#635]
20:25 You see a tower shield (Def:32).
**It can only be wielded properly by sorcerers, master sorcerers, druids, elder druids, paladins, royal paladins, knights and elite knights.**
Imbuements: (Free Slot).
It weighs 82.00 oz. NPC Value: 8,000 gold coins

**Comment by Nahanti** [comment]
Whats wrong with that?

**Comment by kito2** [comment]
Corrected.

@Nahanti they shouldn't be shown on the description.
