### ISSUE TITLE
Yasir - Dracoyle Statue (5000gp)

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#643]
Date | 2019-01-20 16:56:24
-- | --
Player name | Jungle
Position | 32797, 31249, 7
Description | can't sell Dracoyle Statue (5000gp) to Yasir

**Comment by LastCrystal** [comment]
Yasir still doesn't buy normal **Dracoyle Statue** [ID 9035] just the (Enchanted) version.
https://tibia.fandom.com/wiki/Dracoyle_Statue

**Comment by LastCrystal** [comment]
For some reason this item is on his list but you can't sell it.
![image](https://user-images.githubusercontent.com/46424212/52883388-06642980-316b-11e9-87b6-8e4cc55f6b2f.png)

**Comment by LastCrystal** [comment]
Rewrited to another topic.
