### ISSUE TITLE
Small enchanted amethyst

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#649]
Small enchanted amethysts (NPC Value: 200 gold coins) but every npc pays 250gp for it.
https://tibia.fandom.com/wiki/Small_Enchanted_Amethyst

**Comment by LastCrystal** [comment]
Just change the item description :p

**Comment by Kertie** [comment]
### **NPCs**

- [ ] Briasol
- [ ] Chantalle
- [ ] Edmund
- [ ] Gail
- [ ] Ishina
- [ ] Iwan
- [ ] Jessica
- [ ] Hanna
- [ ] Odemara
- [ ] Oiriz
- [ ] Talila
- [ ] Tesha
- [ ] Tezila
- [ ] Valindara
- [ ] Yonan

**Comment by Kertie** [comment]
Carina is buying this item and she shouldn't buy it.

**Comment by joerod1** [comment]
> * Carina is buying this item and she shouldn't buy it.
> * Talila and Valindara are the correct NPCs who are buying the item. However, we have to change the price from 250 gp to 200 gp.

* Carina is not buying
* Talila is buying for 200 gps
* Fixed Valindara price

**Comment by Kertie** [comment]
Okey. I checked it. Now we have to add the rest of NPCs which I wrote on the list above in this issue.

**Comment by Kertie** [comment]
Now it's working.
Closed.
