### ISSUE TITLE
Retching Horror doesn't drop the following:

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#655]
Onyx flail
no loot Sai's/terra mantle/red piece of cloth

Source:B3nek 
https://forum.masteria.net/threads/retching-horror-x2.1587/#post-11786

**Comment by kito2** [comment]
Choking Fear doesn'0t look Sai or Terra Mantle according to Tibia Fandom.

Just added Onyx flail a few hour ago, also steel helmet and butcher's axe to Retching Horror.
