### ISSUE TITLE
bug on speed

### ISSUE THREAD

**Issue by TinSion** [kito2/mtibia-bounties#664]
16:20 Smokusiiek [246]: im changed
16:21 Smokusiiek [246]: orientals with imbu
16:21 Smokusiiek [246]: with boots of haste
16:21 Smokusiiek [246]: and speed going up

when u change ur imbued oriental shoes to boots of haste speed increase to 1000 check on photo
https://imgur.com/a/vUTdQuw

**Comment by DymekPL** [comment]
Fixed
