### ISSUE TITLE
rathleon quest promotions not working neither the achievements you get by promoting from ranks 4 achievement in total.

### ISSUE THREAD

**Issue by kito2** [kito2/mtibia-bounties#669]
Date | 2019-01-17 13:12:13
-- | --
Player name | Puzofugazo
Position | 33627, 31895, 6
Description | rathleon quest promotions not working neither the achievements you get by promoting from ranks 4 achievement in total.

**Comment by LastCrystal** [comment]
**Rathleton Commoner** - Obtained by reaching the rank of Commoner in the Rathleton Quest.
**Rathleton Inhabitant** - Obtained by reaching the rank of Inhabitant in the Rathleton Quest.
**Rathleton Citizen** - Obtained by reaching the rank of Citizen in the Rathleton Quest.
**Rathleton Squire** - Obtained by reaching the rank of Squire in the Rathleton Quest.
