### ISSUE TITLE
Not B Statue. (yes I know, ask GM Kertie :D )

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#694]
Date | 2019-01-20 20:05:34
-- | --
Player name | GM Kertie
Position | 32799, 32828, 15
Description | Not B Statue.

**Comment by Kertie** [comment]
It's related to Lloyd boss.

**Comment by LastCrystal** [comment]
Yes, there is a small visual glitch on this boss but closing this cuz duplicate topic.
