### ISSUE TITLE
Baltim dont buying Frost Giant Pelt.

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#701]
Date | 2019-01-24 12:52:35
-- | --
Player name | GOD Anabelle
Position | 32341, 31322, 6
Description | Baltim dont buying Frost Giant Pelt.

**Comment by Kertie** [comment]
It isn't working. It should be fixed.

**Comment by joerod1** [comment]
> It isn't working. It should be fixed.

added **Frost Giant Pelt** and other creature products

**Comment by Kertie** [comment]
We have to modify its price from 135 gp to 160 gp.

![image](https://user-images.githubusercontent.com/45070560/66079553-90c79500-e564-11e9-996b-fc765d57eb9d.png)

![image](https://user-images.githubusercontent.com/45070560/66079579-9cb35700-e564-11e9-8990-e8d21f4d8044.png)

**Comment by Kertie** [comment]
Now it's working.
Closed.
