### ISSUE TITLE
remake loot from asuras back to normal

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#720]
Date | 2019-01-24 21:14:55
-- | --
Player name | Trewq
Position | 32629, 32743, 7
Description | please remake loot from asuras back to normal killing around 650~ asuras looted only 3 assassin dagger...

**Comment by LastCrystal** [comment]
imo. The loot is fine, I hunt there and always make good profit, asuras drop a lot of good items and there is no need to inscres it. On rl you get like 1 assassin dager per 200 Midnight Asura so i think it's normal.
