### ISSUE TITLE
Monster doesn't count in task

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#73]
Date | 2018-12-20 23:14:27
-- | --
Player name | GM Tin
Position | 32350, 32223, 7
Description | Doesn't count inq gold in Blowing Horns Task in Roshamuul

**Comment by kito2** [comment]
player:setStorageValue(ROSHAMUUL_GOLD_RECORD, inqui_gold+100)

It does count.

Maybe we need more details about WHEN this happened.

**Comment by joseluis2g** [comment]
how can I test this?

**Comment by kito2** [comment]
@joseluis2g here is an example: https://youtu.be/JobEHPYU2xY?t=130

**Comment by joseluis2g** [comment]
I'm going to test this and if its working we can keep this closed.
