### ISSUE TITLE
Travel to Oramond

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#730]
Date | 2019-01-24 17:39:37
-- | --
Player name | Grow Majster
Position | 32954, 32029, 6
Description | **Player said:** You can travel from Venore to Oramond but it shouldn't be possible.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64057374-51400e80-cb9c-11e9-9e39-f4294c259fb6.png)

**Comment by Kertie** [comment]
Now it's working.
Closed.
