### ISSUE TITLE
Re-do Deepling

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#75]
Date | 2018-12-20 23:16:03
-- | --
Player name | GM Tin
Position | 32350, 32223, 7
Description | Re-do Brokul & Neutral Deepling (XML: damages, HP, resistences) then, test configuration for quest

**Comment by joerod1** [comment]
actually done on brokul: 
resistences: 100%
hp: 100%
spells:
```
	done:
		Corpo a corpo (0-1260+) 
		Death Bomb (drena mana) (0-0)
		Self Healing (350-690).
		Holy Beam (0-660)
		Death Beam (0-820)
		Fire Beam (0-840)
		Ultimate Explosion (0-0)
		Fireball (100-870)
		Earth Missile (460-560)
		Drown Wave (0-0)
	
	todo:
		Ice Beam (0-0)
		Poison Berserk (0-0)
```

**Comment by joerod1** [comment]
actually done on Neutral Deepling Warrior:
resistences: 100%
hp: 100%
attacks: 100%

based on: https://tibia.fandom.com/wiki/Neutral_Deepling_Warrior

**Comment by Kertie** [comment]
It's working now.

Closed.
