### ISSUE TITLE
NPC Pemaret on cormaya - you can say hi, kick with pz block

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#757]
Date | 2019-01-26 18:09:53
-- | --
Player name | El Campeon
Position | 33293, 31957, 6
Description | NPC Pemaret on cormaya - you can say hi, kick with pz block

**Comment by LastCrystal** [comment]
You can kick with pz block from any boat. Is this a bug?

**Comment by joseluis2g** [comment]
I guess travel module need to be modified

**Comment by Nahanti** [comment]
Fixed.
