### ISSUE TITLE
cast not working (due to name change?)

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#768]
Forum name; Typloshiion v2

"as topic says since i changed name to Typloshiion on masteria, my cast not showin."

**Comment by Tenzhiro** [comment]
"its not because of your change name, its because casts are only visible for example to letter H, and cast like you or someone else with a name behind letter H are not visible, but still can look on these casts by switch casts using ctrl+arrow"

**Comment by Tenzhiro** [comment]
"This might be an error related to amount of total of casts posible to be shown on client instead."

**Comment by LastCrystal** [comment]
Casts has been fixed, thanks to @Nahanti
