### ISSUE TITLE
Forgotten knowledge quest: The Last Lore Keeper

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#769]
Something here is wrong (idk what - probably timer because we get kicked too fast) . 
We were doing this same like on rl tibia.
https://www.youtube.com/watch?v=ZYjqwJAYQPs
^ check public cam or youtube from our perspective

It should work like that: 
https://gyazo.com/0728a87422c25951933603728360c642

**Comment by LastCrystal** [comment]
Duplicate topic and already reported.
