### ISSUE TITLE
A Sweaty Cyclops Quest - NPC misstake

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#781]
Date | 2019-01-29 15:49:03
-- | --
Player name | Vers Larkez
Position | 32698, 31673, 3
Description | A Sweaty Cyclops Quest we need to say "Uth'lokr yes yes Uth'lokr yes" and it should be "Uth'lokr yes yes bast skirt yes"

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64928494-4b436200-d819-11e9-83f3-9800ba867c3f.png)

Now it's working.
Closed.
