### ISSUE TITLE
cant enter to Tyrsung quara respaw

### ISSUE THREAD

**Issue by Petosss** [kito2/mtibia-bounties#789]
Date | 2019-01-28 20:49:12
-- | --
Player name | Alexanet
Position | 32333, 31117, 7
Description | I cant enter to Tyrsung quara respaw, please fix it

**Comment by Kertie** [comment]
Remember to put a label.

**Comment by Kertie** [comment]
https://youtu.be/jhuOCa2tMAA?t=46

This is a video in which you can see how it works.

https://tibia.fandom.com/wiki/Frozen_Trench
