### ISSUE TITLE
Casks left in house door, can be used by uninvited players.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#792]
Not invited players can use some items left in player house doors, for exaple **ice cubs** **+ obsidian knife** or refiling **potions** from **casks** left in doors.
https://gyazo.com/529a46a8c0632318acb9b825ae52728b

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/65465260-1740f000-de5c-11e9-98a0-20e9edf7a630.png)

Now it's working.
Closed.
