### ISSUE TITLE
Thundergiat needs buff

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#80]
Date | 2018-12-21 02:23:34
-- | --
Player name | Unbench The Kench
Position | 33322, 32324, 12
Description | THUNDERGIANT ONLY EXETA RES 1 1SQM BUT ON RL TIBIA ITS MORE SQMS AND IT TAKES LONGER FOR THUNDERGIANT TO HEAL ON THIS OT

**Comment by Kertie** [comment]
**EXETA RES**
https://vimeo.com/334719543

**HEAL**
https://vimeo.com/334723820

**Comment by joerod1** [comment]
decreased the healing time from 4 to 2.5 seconds
increased exeta res area from 1x1 to 2x2

**Comment by Kertie** [comment]
It's working properly now.
