### ISSUE TITLE
yasir does not buy volatile proto matter, dangerous proto matter and plasmatic lighting and probably many other heart of destruction stuff

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#801]
Date | 2019-01-30 03:30:01
-- | --
Player name | Kolczan
Position | 32336, 31778, 7
Description | yasir does not buy volatile proto matter, dangerous proto matter and plasmatic lighting and probably many other heart of destruction stuff

**Comment by Nahanti** [comment]
added volatile proto matter, dangerous proto matter and plasmatic lighting, if someone reports something more I will add
