### ISSUE TITLE
Debug while exchanging soul orbs.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#807]
I'm getting client debug when trying to exchange a lot of soul orbs for infernal bolts at Sweaty Cyclop, Ab'dendriel.
https://gyazo.com/0e53cb746ce14b8a491b36d25df914bb
Not only that, the brocade bp, I had on while doing it, now can not be sold on market.

**Comment by Nahanti** [comment]
Should be fixed, please check after server save.

**Comment by LastCrystal** [comment]
Works fine now, thanks.
