### ISSUE TITLE
Equip hotkeys

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#81]
Date | 2018-12-21 02:34:28
-- | --
Player name | GM Kertie
Position | 32318, 31934, 7
Description | Equip hotkeys are bugged. If you stay pressed it, it will be equipping / unequipping so faaaast.

**Comment by Kertie** [comment]
https://vimeo.com/334422456

**Comment by Kertie** [comment]
This is the issue which should be moved to projects on the private GitHub repository. @kito2

**Comment by kito2** [comment]
Moved to projects.
