### ISSUE TITLE
Wrong item weights part 2.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#828]
- [x] **Protection Amulet** weight is 9.50 oz, should be **5.50 oz.** 
- [x] **Silver Amulet** weight is 15.00 oz, should be **5.00 oz.**
- [x] **Axe ring** weight is 5.90 oz, should be **0.90 oz.**
- [x] **Club Ring** weight is 5.90 oz, should be **0.90 oz.**
- [x] **Sword Ring** weight is 5.90 oz, should be **0.90 oz.**
- [x] **Bat Decoration** weight is 10.00 oz, should be **2.00 oz.**
- [x] **Trophy of Feroxa** weight is 1.20 oz, should be **5.00 oz.**
- [x] **Werebear Trophy** weight is 5.90 oz, should be **5.00 oz.**
- [x] **Werebadger Trophy** weight is 1.00 oz, should be **5.00 oz.**
- [x] **Wereboar Trophy** weight is 2.00 oz, should be **5.00 oz.**
- [x] **Moonlight Crystals** weight is 4.40 oz. should be **4.00 oz.**
- [x] **Blue Gem** weighs is 1.00 oz, should be **0.30 oz.**
- [x] **Empty Flower Pot** weight is 15.00 oz, should be **1.50 oz.**
- [x] **Watering Can** weight is 28.50 oz, should be **8.50 oz.**
- [x] **Watch** weight is 25.00 oz, should be **0.50 oz.**
- [x] **Party Trumpet** weight is 5.00 oz, should be **0.50 oz.**
- [x] **Rolling Pin** weight is 15.00 oz, should be **5.00 oz.**
- [x] **Candlestick** weight is 30.00 oz, should be **3.00 oz.**
- [x] **Rake** weight is 25.00 oz, should be **15.00 oz.**
- [x] **Bucket** weight is 2.00 oz, should be **20.00 oz.**
- [x] **Letter** weight is 5.00 oz, should be **0.50 oz.**
- [x] **Label** weight is 1.00 oz, should be **0.10 oz.**
- [x] **Hammer** weight is 21.50 oz, should be **11.50 oz.**
- [x] **Party Cake** weight is 5.00 oz, should be **7.00 oz.**
- [x] **Scale of Gelidrazah** has no weight, should have **5.00 oz.**
- [x] **Horn of Kalyassa** has no weight, should have **6.50 oz.**
- [x] **Tooth of Tazhadur** has no weight, should have **3.50 oz.**
- [x] **Bones of Zorvorax** has no weight, should have **8.00 oz.**
- [x] **Dragon Tongue** has no weight, should have **5.50 oz.**
- [x] **Dragon Blood** has no weight, should have **3.50 oz.**
- [x] **Golden Talon** has no weight, should have **6.50 oz.**
- [x] **Shadow Paint** has no weight, should have **6.50 oz.**
- [x] **Shadow Mask** has no weight, should have **6.50 oz.**
- [x] **Dragon Crown** has no weight, should have **6.50 oz.**
- [x] **Frozen Time** has no weight, should have **6.50 oz.**
- [x] **Forbidden Fruit** has no weight, should have **6.50 oz.**
- [x] **Thorn Seed** has no weight, should have **6.50 oz.**
- [x] **Coal Eyes** has no weight, should have **6.50 oz.**
- [x] **Glowing Carrot** has no weight, should have **6.50 oz.**
- [x] **Imbuing Crystal** has no weight, should have **2.50 oz.**
- [x] **Part of a Rune (1,2,3,4,5,6)** have no weights, they should have **8.50 oz.**

**Comment by Nahanti** [comment]
Corrected.

**Comment by LastCrystal** [comment]
This list still hasn't been corrected.

**Comment by Kertie** [comment]
Forbidden Fruit still not have weight.

**Comment by Kertie** [comment]
Closed.
