### ISSUE TITLE
Achivement is missing and wrong reward from chest.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#84]
Date | 2018-12-21 11:05:57
-- | --
Player name | GOD Khaz
Position | 33271, 31838, 6
Description | It's supposed to be here "nature magic spellbook" + achievment

**Comment by LastCrystal** [comment]
The "nature magic spellbook" is obtained from a drawer, 3 flors higher at (33269, 31839, 3) so shouldn't be here different reward? Also anyone can enter the red handle door at (33271, 31838, 6).

**Comment by kito2** [comment]
@Nahanti can you provide more information about this achievement?

**Comment by kito2** [comment]
This is for https://tibia.fandom.com/wiki/Secret_Service_Quest

Already moved to private git.

**Comment by LastCrystal** [comment]
It should be there Old Pirate Poem (Book) for Treasure Hunt Quest.

**Comment by kito2** [comment]
This quests is not enabled I guess, so it should be written as a new issue.
