### ISSUE TITLE
Golden Servant loot

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#842]
Date | 2019-02-03 18:25:05
-- | --
Player name | Er'bloker
Position | 33360, 31914, 9
Description | **Player said:** fix **Golden Servant/Diamond Servant's** loot: they dont drop Golden Armor/Crystalline Armor/Bonebreaker

**Comment by Infermus** [comment]
Well, never drop a single Golden Armor/Crystalline Armor/Bonebreaker at realtibia. Keep in mind that I done like 200 runs of raiging mage, so those items are extermly rare.
Anyway we should test it @Kertie

**Comment by Kertie** [comment]
@Infermus I add this issue to muy task list in order to test as soon as possible.

**Comment by Kertie** [comment]
### **LOOT TRACK**

- [ ] 0-140x Gold Coin
- [ ] Health Potion
- [ ] Mana Potion
- [ ] Halberd
- [ ] Green Mushroom
- [ ] Gear Wheel
- [ ] Spellbook of Enlightenment
- [ ] Stealth Ring
- [ ] Slime Mould
- [ ] Golden Can of Oil
- [ ] Golden Armor
- [ ] Gold Ring

**Comment by Kertie** [comment]
It's working.
Drop % are similar to RL, so it's difficult to loot these items.

Closed.
