### ISSUE TITLE
Improved loot prey

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#843]
Date | 2019-02-03 20:22:27
-- | --
Player name | Salice
Position | 33121, 31725, 14
Description | **Player said:** I think that prey bonus "improved loot" doesn't work, please check it.

**Comment by Eazyest** [comment]
I checked this case on two different monsters with loot prey 10/10. With each killed monster I could see a message on the loot channel saying about the active bonus (screenshot), but in none of the 40 killed monsters there were no duplicated items as it does on real Tibia (like gold coins + gold coins from prey)
![image](https://user-images.githubusercontent.com/46423683/52541251-34c0be00-2d93-11e9-8794-19c84c632e44.png)

**Comment by kito2** [comment]
The prey system works different here rather than RL, we don't duplicate loot chances here; so there won't be duplicated items when looted, it only gives double the chance to loot certain items.

**Comment by joseluis2g** [comment]
we can also fix this

**Comment by kito2** [comment]
Indeed but I dont like how it works on RL... sounds a little OP.

**Comment by joseluis2g** [comment]
I really think this is well done but maybe Im missing something, like I do not think prey messages should always appear (not sure if its like this now)

**Comment by kito2** [comment]
Indeed, it should be only triggered when 10/10 only 40% of times and instead of increasing the loot chance, it should double all items in loot table twice, this means it is double chance to loot each item.

**Comment by joseluis2g** [comment]
not really double chances but like you killed 2 monsters in 1
