### ISSUE TITLE
Npc Tarak wrong Transcripts

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#844]
Date | 2019-02-04 10:21:54
-- | --
Player name | Pain Of
Position | 32936, 31185, 11
Description | **Player said:** Npc Tarak should react to text hi trip yes, instead he just react to hi monument tower yes. small bug but still, my bot cracking cuz of that , and hhe really should react to word "Trip"

**Comment by Kertie** [comment]
- [ ] Hi / Trip / Yes
- [ ] Hi / Monument Tower / Yes

We should make possible to travel using both transcripts.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64292074-d2ffb580-cf69-11e9-9d56-f0bdb6aec6c6.png)

Closed.
