### ISSUE TITLE
Machine on factory yalahar

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#85]
Date | 2018-12-21 11:08:49
-- | --
Player name | Grosiu
Position | 32886, 31215, 7
Description | Player said: I put 4 gear whell to the machine on the factory yalahar but you can not enter the war golems

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/58424458-b402a500-8097-11e9-8e1f-49b5db002c56.png)

It's working properly. 4 Gear Wheels to open the teleport + 1 Gear Wheel to pass through the teleport.
Closed.
