### ISSUE TITLE
Can't sell wedding ring.

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#850]
Date | 2019-02-05 21:31:12
-- | --
Player name | Aven
Position | 33085, 32873, 7
Description | **Player said:** Can't sell wedding ring to NPCs.

**Comment by LastCrystal** [comment]
https://tibia.fandom.com/wiki/Wedding_Ring

**Comment by Kertie** [comment]
- [ ] Briasol
- [ ] Carina
- [ ] Chantalle
- [ ] Edmund
- [ ] Gail
- [ ] Hanna
- [ ] Ishina
- [ ] Iwan
- [ ] Jessica
- [ ] Odemara
- [ ] Oiriz
- [ ] Talila
- [ ] Tesha
- [ ] Tezila
- [ ] Valindara
- [ ] Yonan

**Comment by Kertie** [comment]
There are two NPCs from the list which didn't buy your ring.
Carina and Yonan. The second one doesn't exit on MTibia.

**Comment by joerod1** [comment]
what about Yonan. Is him important?

**Comment by Kertie** [comment]
Not now.
He had been implemented on version 12.20

**Comment by Kertie** [comment]
Carina is now buying Wedding Ring. However, we have to change this NPC --> #1148 

![image](https://user-images.githubusercontent.com/45070560/64291889-77352c80-cf69-11e9-91e8-529c1bc95964.png)
Closed.
