### ISSUE TITLE
NPC Appaloosa - Venore - npc where u can rent horse. 500 per rent, but u need 501 in bp to rent this horse.

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#857]
Date | 2019-02-06 22:27:05
-- | --
Player name | GM Dymek
Position | 32850, 32123, 7
Description | NPC Appaloosa - Venore - npc where u can rent horse. 500 per rent, but u need 501 in bp to rent this horse.

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64026679-8407e980-cb3f-11e9-90af-4e227e7c667d.png)

Now it's working.
Closed.
