### ISSUE TITLE
Falcon coif

### ISSUE THREAD

**Issue by TinSion** [kito2/mtibia-bounties#864]
You see an falcon coif (Arm:10, distance fighting +2, shielding +2, protection physical +3%, fire +10%).
It can only be wielded properly by paladins and knights of level 300 or higher.
It weighs 28.00 oz.
 < Dont have sloots for imbue

Imbuable | ✓ <<< 
Imbuing slots | 2 <<<

**Comment by LastCrystal** [comment]
Falcon coif now will get properly two imbuiments slots.
