### ISSUE TITLE
on ice fishing you can fish only normal fish - you should fishing other fish.

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#869]
Date | 2019-02-09 21:55:34
-- | --
Player name | Mokri Majmun
Position | 32330, 31073, 7
Description | on ice fishing you can fish only normal fish - you should fishing other fish.

**Comment by Infermus** [comment]
Fishing specific fishes depends of player fishing skill.

Results of fishing while skill = 10: ( 50 tries)
![image](https://user-images.githubusercontent.com/35379749/66077231-d9c91a80-e55f-11e9-9ecd-4fdcbfd5475c.png)

Results of fishing while skill = 80: ( 200 tries)
![image](https://user-images.githubusercontent.com/35379749/66077278-ecdbea80-e55f-11e9-9aaa-bc828cf9cde4.png)

So it's possible to get all fishes from ice, but loot rate is too low. Should be boosted a little.

**Comment by Kertie** [comment]
We will keep the same drop rates at the moment.
Closed.
Thnks you @Infermus
