### ISSUE TITLE
wrong info on Krailos task screen/broadcast message

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#888]
https://cdn.discordapp.com/attachments/545278721330774036/545953204211548161/unknown.png
https://cdn.discordapp.com/attachments/545278721330774036/545953266413076481/unknown.png

The task should be changed from 800 to 500
See https://www.masteria.net/library/tasks, unique tasks, Krailos.

**Comment by LastCrystal** [comment]
Corrected.
