### ISSUE TITLE
Yasir items

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#892]
**Yasir** doesn't buy:

- [x] **Badger Fur** | ID **11216** - 15 gp
- [x] **Crystallized Anger** | ID **26163** - 400 gp
- [x] **Dracoyle Statue** | ID **9949** - 5000 gp
- [x] **Energy Vein** | ID **26164** - 270 gp
- [x] **Glowing Rune** | ID **32214** - 350 gp
- [x] **Grant of Arms** | ID **32468** - 950 gp
- [x] **Fox Paw** | ID **30757** - 100 gp
- [x] **Instable Proto Matter** | ID **26172** - 300 gp
- [x] **Odd Organ** | ID **26166** - 410 gp
- [x] **Rhino Horn** | ID **27045** - 265 gp
- [x] **Rhino Hide** | ID **27044** - 175 gp
- [x] **Yellow Piece of Cloth** | ID **5914** - 150 gp
- [x] **Zaogun Shoulderplates**| ID **11331** - 150 gp ( After delivering 9 Tomes of Knowledge to Cael)

(these are Masteria client IDs)

**Comment by Kertie** [comment]
There are two items called badge fur: this one shouldn't be available to sell.
![image](https://user-images.githubusercontent.com/45070560/64034096-3b0b6180-cb4e-11e9-9027-f9b566347ca5.png)

There are 3 dracoyle statues (don't know if it should be like it is now)
![image](https://user-images.githubusercontent.com/45070560/64034217-8160c080-cb4e-11e9-89f6-ad8206a58fb6.png)

The 2 items that aren't marked on the list doesn't exit on MTibia right now.

**Comment by joerod1** [comment]
> There are two items called badge fur: this one shouldn't be available to sell.
> ![image](https://user-images.githubusercontent.com/45070560/64034096-3b0b6180-cb4e-11e9-9027-f9b566347ca5.png)
> 
> There are 3 dracoyle statues (don't know if it should be like it is now)
> ![image](https://user-images.githubusercontent.com/45070560/64034217-8160c080-cb4e-11e9-89f6-ad8206a58fb6.png)
> 
> The 2 items that aren't marked on the list doesn't exit on MTibia right now.

* about the badger, removed
* about the other thing, there are 4 ids of that item, i'm not sure which one it needs to be sold, i'd put all of them
![Captura de pantalla de 2019-09-01 19-01-41](https://user-images.githubusercontent.com/26337790/64083284-3c25c580-cceb-11e9-8f8f-10e0cd3dba0c.png)

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64290185-e872e080-cf65-11e9-92bd-919140b1aec9.png)

Now we have to add Badger Fur (Item ID: 11216) @joerod1

**Comment by Kertie** [comment]
Glowing Rune | ID 32214 - 350 gp
Grant of Arms | ID 32468 - 950 gp

We have to add these two items to Yasir's trade list.

**Comment by Kertie** [comment]
Now it's working.
Closed.
