### ISSUE TITLE
afflicted outfit  doesn't grant the beak doctor achievement

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#903]
Date | 2019-02-18 04:39:31
-- | --
Player name | Bullet Sponge
Position | 33169, 31813, 9
Description | completing the afflicted outfit/addons doesn't grant the beak doctor achievement even tho it's supposed to

**Comment by Kertie** [comment]
This report is true. However, we are working on Achievements in other issue.

So, closed.
