### ISSUE TITLE
Using a batch of cake dough on an oven,  it uses all the cake dough to give you 1 cake

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#908]
Date | 2019-02-19 05:45:10
-- | --
Player name | Brabus Amg
Position | 33173, 31801, 6
Description | Using a batch of cake dough on an oven, for example 50x cake dough, it uses all the cake dough to give you 1 cake

**Comment by DymekPL** [comment]
https://github.com/kito2/mtibia-bounties/issues/816

Duplicated
