### ISSUE TITLE
when doing the beggar outfit does not take away the items you need to do the "outfit"

### ISSUE THREAD

**Issue by Tenzhiro** [kito2/mtibia-bounties#930]
al hacer el beggar outfit no te quita los items que necesitas para hacer el "outfit"
when doing the beggar outfit does not take away the items you need to do the "outfit"

**Comment by Tenzhiro** [comment]
might be fake .. since I got the outfit and im sure it took the staff, NOT 100% sure about the ape fur etc

**Comment by Kertie** [comment]
This report is false.

Closed.
