### ISSUE TITLE
Door at secret service TBI

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#932]
I think this door at **Position(32644, 32734, 7)** should be locked and access to room with the chest only by red handle door. Quest works but it confuses players cuz they don't know that have to step in to this room thu red handle door in order to spawn pirates and update quest log.
![image](https://user-images.githubusercontent.com/46424212/53129307-8291af00-3567-11e9-94e9-4446d44a5240.png)

**Comment by Infermus** [comment]
![image](https://user-images.githubusercontent.com/35379749/66084644-7941d980-e56f-11e9-9b43-b2f756290b88.png)

Can be closed @Kertie

**Comment by Kertie** [comment]
It's supposed to enter using the Quest's door and it's working.
So, closed.

Thank you @Infermus
