### ISSUE TITLE
Missing pz Falcon boat

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#947]
Here should be pz, around this boat **Position(33327, 31351, 7)**
![image](https://user-images.githubusercontent.com/46424212/53274957-8f460c80-36f9-11e9-959f-a690580fb706.png)
And at the other side around this boat **Position(33355, 31343, 7)**
Also please remove that you enter this place by right clicking Position(33328, 31352, 7) without any quest
![image](https://user-images.githubusercontent.com/46424212/54326579-160a4d00-4607-11e9-8e47-9415a1f82503.png)

**Comment by Infermus** [comment]
You can't enter into Falcon Bastion without making access now, so it's working. Pz is also fixed.

![image](https://user-images.githubusercontent.com/35379749/66001870-b4c2a200-e4a2-11e9-84b5-e43f2f1dd139.png)

**Comment by Kertie** [comment]
Now it's working.
Closed. Thanks @Infermus
