### ISSUE TITLE
Locked door at falcon bastion

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#949]
This door at **Position(33369, 31344, 4)** should no be locked, it's relly anoying cuz you have to run arount it every time.
![image](https://user-images.githubusercontent.com/46424212/53275680-4a6fa500-36fc-11e9-9da1-9a55a853718d.png)
On rl those doors are always open and you don't even need a key for them.

**Comment by Infermus** [comment]
![image](https://user-images.githubusercontent.com/35379749/66000634-25b48a80-e4a0-11e9-90be-215e282dec67.png)

Without using any key

**Comment by Kertie** [comment]
Closed.

@Infermus Thanks again!
