### ISSUE TITLE
Missing doors and low falcon spawn

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#950]
This room should have door at **Position(33384, 31313, 2)** and **Position(33387, 31317, 2)** so you could fight the boss and not worrying about other falcons. Also there should be **2x more falcon paladins** at this level.
![image](https://user-images.githubusercontent.com/46424212/53276811-1b0f6700-3701-11e9-8fb7-888766970f67.png)

**Comment by Infermus** [comment]
Doors are different, but in this case it doesn't matter, doors are doors.

Masteria:
![image](https://user-images.githubusercontent.com/35379749/66000955-ce62ea00-e4a0-11e9-86f4-6f605b505160.png)

Real Tibia:
![image](https://user-images.githubusercontent.com/35379749/66001045-f81c1100-e4a0-11e9-9920-736e1bcb3a2e.png)

Decide if we gonna close it or wait for change doors :P @Kertie

**Comment by kito2** [comment]
We will leave them as they are.
