### ISSUE TITLE
NPC Edvard sells bad ID of box. He sell box ID 7484, but he should sell box ID 1738

### ISSUE THREAD

**Issue by DymekPL** [kito2/mtibia-bounties#979]
Date | 2019-02-28 06:08:08
-- | --
Player name | GM Dymek
Position | 32051, 32199, 7
Description | NPC Edvard sells bad ID of box. He sell box ID 7484, but he should sell box ID 1738

**Comment by Kertie** [comment]
![image](https://user-images.githubusercontent.com/45070560/64026066-553d4380-cb3e-11e9-8ea5-6b5e8b1f510b.png)

Now it's working.
Closed.
