### ISSUE TITLE
Imbued raiments can't be sold on market

### ISSUE THREAD

**Issue by LastCrystal** [kito2/mtibia-bounties#996]
Date | 2019-03-01 09:54:38
-- | --
Player name | Methadone
Position | 32422, 31768, 7
Description | **Players said:** Raiments that used to had imbuing slots buffed, now can't be sold on market.

**Comment by LastCrystal** [comment]
I think this is fixed cuz I can sell my armor right now or the invisible imbu disappear over time.

**Comment by joseluis2g** [comment]
its because they removed those imbuiments while item slots still with time remaining
